### ISSUE TITLE
Does this plugin support syncing org format notes?

### ISSUE THREAD

**Issue by zhengyangfeng00** [debanjandhar12/logseq-anki-sync#1]
Hi, I'm using org format to save my notes in logseq. After using this plugin to sync the cards to anki, I found that the formats of all cards are broken. For example, only the top level notes are displayed and I cannot expand any of them.

Is org format file supposed to work?

**Comment by debanjandhar12** [comment]
I am afraid org mode is not supported at the moment as the plugin uses an external markdown parser.

However, I plan on trying to support it by switching to mldocs (parser used by logseq) instead after alpha testing is complete.

**Comment by WaytrueDeng** [comment]
I met this problem too, waiting for the update, hoping it won't be so long. Thanks again.

**Comment by debanjandhar12** [comment]
> I met this problem too, waiting for the update, hoping it won't be so long. Thanks again.

It's almost done but I am currently in the midst of exams. It will take around the 24th of this month for this to be released.

**Comment by debanjandhar12** [comment]
Basic Org mode support has been released in v1.0.0. Please create separate issues if you encounter any problem with org mode.
