### ISSUE TITLE
An error occurred

### ISSUE THREAD

**Issue by qiuzhenyuan** [debanjandhar12/logseq-anki-sync#10]
![image](https://user-images.githubusercontent.com/16810005/147723522-c218d446-9b8d-4a0f-b50c-2a7b12a8159d.png)
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.49 (dc80804a) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Mac 10.16
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2021-12-30 12:25:56

Socket error
Traceback (most recent call last):
  File "waitress/channel.py", line 121, in handle_write
  File "waitress/channel.py", line 259, in _flush_some
  File "waitress/wasyncore.py", line 431, in send
OSError: [Errno 41] Protocol wrong type for socket

**Comment by debanjandhar12** [comment]
Can you give me some more details? Specifically:

Anki and AnkiConnect Version:
Does the error happen when you try to sync?:

**Comment by qiuzhenyuan** [comment]
> Can you give me some more details? Specifically:
> 
> AnkiConnect Version: Does the error happen when you try to sync?: What other Anki plugins do you have installed?:

The error doesn't happen again after i update the plugin to 0.3.1. Thank you !
