### ISSUE TITLE
The <a> tag is translated to html symbol in some situations.

### ISSUE THREAD

**Issue by WaytrueDeng** [debanjandhar12/logseq-anki-sync#101]
the original org file content

* 病毒性肝炎的病理改变包括? #card  
	**  Encode:[[变质]],[[渗出]],[[增生并存]],但是以 [[变质]]为主  

<img width="1470" alt="image" src="https://user-images.githubusercontent.com/61548208/188319113-c6423477-125f-4fac-8cda-718dd6170c35.png">

**Comment by WaytrueDeng** [comment]
I find that if I add space before and after [[]] link, it will be transformed to right formation

**Comment by lijianhuied** [comment]
这应该是中文和英文的语法习惯不同所导致，英文每个单词后面都要跟着空格，中文则不必；

期待适配中文 👍 😄 非常优秀的插件

**Comment by debanjandhar12** [comment]
The main cause of this is mldocs doesn't recognize html tags that have no space before it. One soln. to this is to hide the tag from mldocs.

I will fix this in next version which will be released after whiteboards get merged branch in logseq.

**Comment by debanjandhar12** [comment]
Fixed. I will be available in next release.
