### ISSUE TITLE
card with math error

### ISSUE THREAD

**Issue by xiang578** [debanjandhar12/logseq-anki-sync#102]
card in logseq:
![image](https://user-images.githubusercontent.com/12624910/188367952-12840c69-78c7-4ad0-b34f-970385463ecd.png)

the embedd line raw format:

![image](https://user-images.githubusercontent.com/12624910/188368032-3316ec2c-8fe9-4460-8c09-41164b4eb55f.png)

after sync to anki:

![image](https://user-images.githubusercontent.com/12624910/188368095-1fb2e596-3447-4114-9442-0988f77911aa.png)

![image](https://user-images.githubusercontent.com/12624910/188368117-48fa7a00-cf93-4ae6-a144-cb4551b8668d.png)

**Comment by debanjandhar12** [comment]
Please paste the math content here so I can reproduce the issue.

**Comment by xiang578** [comment]
> Please paste the math content here so I can reproduce the issue.

${L(\hat{y}) = - y \frac{\hat{y}^{1-p}}{1-p} + \frac{\hat{y}^{2-p}}{2-p}, 1<p<2}$

**Comment by debanjandhar12** [comment]
Can you give me the top line as well? I am failing to reproduce the issue on my end.
![image](https://user-images.githubusercontent.com/49021233/188556530-ba1d1645-6d59-4095-b164-8cefc1a248d0.png)

**Comment by xiang578** [comment]
> Can you give me the top line as well? I am failing to reproduce the issue on my end. Also, include OS version please. ![image](https://user-images.githubusercontent.com/49021233/188556530-ba1d1645-6d59-4095-b164-8cefc1a248d0.png)

i think i find the problem，when i embedd the formula to card，it will be wrong，such as 1 in picture.

<img width="1269" alt="image" src="https://user-images.githubusercontent.com/12624910/188652642-8d90aa18-2836-4032-8e89-cb53ea6d665e.png">

**Comment by xiang578** [comment]
> > Can you give me the top line as well? I am failing to reproduce the issue on my end. Also, include OS version please. ![image](https://user-images.githubusercontent.com/49021233/188556530-ba1d1645-6d59-4095-b164-8cefc1a248d0.png)
> 
> i think i find the problem，when i embedd the formula to card，it will be wrong，such as 1 in picture.
> 
> <img alt="image" width="1269" src="https://user-images.githubusercontent.com/12624910/188652642-8d90aa18-2836-4032-8e89-cb53ea6d665e.png">

@debanjandhar12 can you look how to fix this problem?

**Comment by debanjandhar12** [comment]
Fixed. I will be available in next release.

**Comment by xiang578** [comment]
> Fixed. It will be available in next release.

thank your, this plugin help me learning very much.

**Comment by xiang578** [comment]
> Fixed. It will be available in next release.

when will you plan to release new version?

**Comment by debanjandhar12** [comment]
> > Fixed. It will be available in next release.
> 
> when will you plan to release new version?

It will take a few days - around a week more. Currently, the production build is broken (dev build works).
