### ISSUE TITLE
Arrow cards have problems with underlines and subscripts

### ISSUE THREAD

**Issue by Tubo** [debanjandhar12/logseq-anki-sync#104]
**Describe the bug**
In Logseq, I write: 

`mesoblastic nephroma should not be confused with :-> _multilocular cystic nephroma_`

In Anki, I get:

`<p>Mesoblastic nephroma should not be confused with <b>:-&gt;</b> {{c1::<sub>multilocular</sub> cystic nephroma<sub>,</sub> which is a cystic renal mass with a bimodal age distribution, and is not related to the metanephric blastema.}}</p>`

**Expected behavior**
The content after the `:->` should be underlined, but instead it's treated as subscripts.

**Device Information (please complete the following information):**
 - OS with version: Linux
 - Logseq Anki Sync Plugin Version: Latest 
 - Anki Version: 2.1.54
 - AnkiConnect Addon Version: ankiconnect-22.7.14.0
 - Logseq Version: 0.8.5

**Comment by Tubo** [comment]
I did some testing, the bug only appears when the first character after `:->` is underline. Even a `.` such as  `mesoblastic nephroma should not be confused with :-> ._multilocular cystic nephroma_` works correctly.

**Comment by debanjandhar12** [comment]
Please check whether it's fixed on not (in [v3.2.4](https://github.com/debanjandhar12/logseq-anki-sync/releases/tag/v3.2.4)). I was able to reproduce the link bug but not the subscript one.

**Comment by Tubo** [comment]
> Please check whether it's fixed on not (in [v3.2.4](https://github.com/debanjandhar12/logseq-anki-sync/releases/tag/v3.2.4)). I was able to reproduce the link bug but not the subscript one.

Can confirm it's fixed. Thanks.
