### ISSUE TITLE
Can't display images coming from block ref

### ISSUE THREAD

**Issue by piskel** [debanjandhar12/logseq-anki-sync#107]
**Describe the bug**
Images in the answer of the cards can't be displayed if they are coming from a block and are replaced with a text version of the link to the picture.

**Steps to Reproduce:**

1. Go to an image in a page
2. Copy the block ref of the image in the page (right click "Copy block ref")
![image](https://user-images.githubusercontent.com/10447278/194004849-dd19c688-5fac-4620-b462-ae5734a6a5c3.png)

3. Put the copied block ref in the answer of a card ![image](https://user-images.githubusercontent.com/10447278/194004728-b2f110de-76fb-41b7-aac4-1fd8c3de8ed5.png)

4. Sync to Anki with the plugin
5. The image is not displayed and only a text link is visible
![image](https://user-images.githubusercontent.com/10447278/194005209-42ca56dd-7e0b-46e9-9fd6-2cac6c1e3a7b.png)

**Expected behavior**
The image should have been displayed like this:
![image](https://user-images.githubusercontent.com/10447278/194005543-1c835284-e0f6-4411-82f4-48d2a3953b31.png)

**Device Information (please complete the following information):**
- OS with version: [Windows 11 Home 21H2]
- Logseq Anki Sync Plugin Version: [0.3.2.3]
- Anki Version: [2.1.54]
- AnkiConnect Addon Version: [22.9.18.0]
- Logseq Version: [0.8.8]

**Comment by debanjandhar12** [comment]
Fixed. I will be available in next release.
