### ISSUE TITLE
Some directory (parent) card with all the next levels(all next children block)

### ISSUE THREAD

**Issue by lijianhuied** [debanjandhar12/logseq-anki-sync#108]
Hey
- I hope that the plug-in can generate not only an Anki card with labels(#card), but also a directory (parent) card. The answer to each parent card is all the **next** levels(all **next** children block)，just Like the picture below。  
	- ![image](https://user-images.githubusercontent.com/64068071/195119552-ee652d8c-d64a-4e43-809f-377f7132c765.png)
	- ![image](https://user-images.githubusercontent.com/64068071/195119673-3bd48624-a03b-477f-a941-aba032f2eb72.png)
	- ![image](https://user-images.githubusercontent.com/64068071/195119748-80f80474-a08c-4050-b5a0-262ae9722f43.png)
- However,v3.2.4 will export all the next levels(all children block),just like below picture
        - ![image](https://user-images.githubusercontent.com/64068071/195119945-40e8f253-70ff-449b-81a6-f0311ed7d9c9.png)****

**Comment by lijianhuied** [comment]
> It is possible to limit the depth of children using `#depth-1` tag. Please see #88.
> 
> Is this what you wanted to achieve?

Thank you very much！This is what I expect；
By the way,if all my notes follow this structure, then the tag (# card) has no substantive meaning;
---
## Personally, if we take notes like this, we can export each lower level as the answer of the upper level to Anki instead of labeling each block;Thanks again1😄

**Comment by debanjandhar12** [comment]
> ## And,for an obsessive-compulsive disorder, this information redundancy is uncomfortable;Whether these labels(#card #depth-1 or any other label) can be placed in a field separately?
> ![image](https://user-images.githubusercontent.com/64068071/195625200-66e51e01-a09c-43c6-9fe5-f223ffb5b48a.png)

There are a few reasons why `#depth-1` cannot be treated as `#card`:
- Performance will degrade.
- The `#depth-1` is kept reserved for future use in setting depth of page & block embedded etc..

**Comment by lijianhuied** [comment]
> 

Yeah;And thank you for reply my question 😄
