### ISSUE TITLE
Logseq tags imported into anki tags

### ISSUE THREAD

**Issue by kimo-supremo** [debanjandhar12/logseq-anki-sync#110]
**Describe the solution you'd like**
I would like to import Logseq tags as anki tags rather than just #text as shown in the pictures
![Screen Shot 2022-10-12 at 10 57 06 PM](https://user-images.githubusercontent.com/70135155/195436254-8723f7b5-c27e-4e10-9824-15ea81245ad8.png)
![Screen Shot 2022-10-12 at 10 56 23 PM](https://user-images.githubusercontent.com/70135155/195436208-cd55b51e-0294-4f36-a6a0-428cb6fe9540.png)
![Screen Shot 2022-10-12 at 10 56 37 PM](https://user-images.githubusercontent.com/70135155/195436237-eea94a04-098b-4d1a-94ab-9a57a6782b33.png)

**Describe how it will help your workflow**
It will help me keep my anki cards much more organized by grouping them by tags as they are organized on logseq.

**Describe alternatives you've considered**
Not really. The only alternative would be to manually do all the cards tags but that would be ruined on sync.

**Comment by lijianhuied** [comment]
> 

Yeah,i want this feature too;
In fact,use regex to remove labels in "text" field,then,import Logseq tags as anki tags.
This is my preliminary idea. I look forward to the author's reply.

**Comment by debanjandhar12** [comment]
This will be included in v4.0.0.

**Comment by kimo-supremo** [comment]
ETA on v4.0.0? thanks a lot btw!

**Comment by debanjandhar12** [comment]
> ETA on v4.0.0? thanks a lot btw!

It will take a few days - around a week or two. Currently, the production build is broken.

In the meanwhile, you can make a dev build and use it if you want.
