### ISSUE TITLE
Some regex replacement problem

### ISSUE THREAD

**Issue by lijianhuied** [debanjandhar12/logseq-anki-sync#112]
Hey!
**Describe the bug**
When i paste other App link into Logseq,like"bookxnotepro://opennote/?nb={8d41cc84-5b4b-4224-a32c-85bac9f3be73}&book=debd532b97314544b76762a4e633e4d2&page=142&x=268&y=181&id=29&uuid=3cfb3e4a58360c1fda7122acfc4e0ace",the plugin wil replace "//"to blank,as picture bellow;
![image](https://user-images.githubusercontent.com/64068071/196869939-b69f7e1e-5b7d-4d88-afb8-252cf95fc8aa.png)

**Device Information (please complete the following information):**
 - OS with version: [e.g. Windows 10] 
 - Logseq Anki Sync Plugin Version: [e.g. 3.2.4]
 - Anki Version: [e.g. 2.1.47]
 - AnkiConnect Addon Version: [e.g. 2.1.0]
 - Logseq Version: [e.g. 0.8.8]

**Comment by debanjandhar12** [comment]
I will look into it.

Closing it for now as It is being tracked on #74.
