### ISSUE TITLE
Anki Sync creates duplicates in Anki

### ISSUE THREAD

**Issue by DerOeko** [debanjandhar12/logseq-anki-sync#12]
Hey! First of all, thank you for your work!!

I've been wondering if this is meant to be this way or not, but when I sync my LogSeq with Anki, it keeps creating the same notes over and over again, always with the same uuid
![grafik](https://user-images.githubusercontent.com/58188566/147856676-894a55c4-91ee-4051-a8da-48533bbf6173.png)
![grafik](https://user-images.githubusercontent.com/58188566/147856705-5ab511f3-ddfe-4c2b-b1ff-982a0138d12c.png)

I am currently on Windows :) 

Best regards
Sam!

**Comment by debanjandhar12** [comment]
This seems like a bug.

Can you give me some more details? Specifically:
- Logseq Version:
- Logseq Anki Sync plugin Version:
- Logseq Graph Name:
- Anki and AnkiConnect Version:
- Screenshot of Logseq's Developer Console (if possible):

**Comment by DerOeko** [comment]
Sure! 

Graph name: "Second Brain"
Logseq Version: 0.4.4
Logseq Anki Sync plugin Version: 0.2.0
Anki Version: 2.1.43
AnkiConnect Version: Latest Version (when checked for updates, there isn't one available)

I unfortunately don't know how to open the Developer Console, if you tell me how I can hand in a screenshot later!

**Comment by debanjandhar12** [comment]
This is a known bug and was fixed in v0.2.2 of Logseq Anki Sync plugin Version.
[![image](https://user-images.githubusercontent.com/49021233/147872373-bb034b0e-e7ca-43e7-b883-d8ba60218b08.png)
](https://github.com/debanjandhar12/logseq-anki-sync/releases/tag/v0.2.2)

Please try updating to latest version (v0.3.1) and check?

**Comment by DerOeko** [comment]
Awesome! Works like a charm now, thank you very much!
