### ISSUE TITLE
hide the breadcrumb

### ISSUE THREAD

**Issue by superouioui** [debanjandhar12/logseq-anki-sync#124]
Have the possibility to hide the page name/breadcrumb in the Anki's flashcards. 
Because in the page names there are often the answer.
<img width="334" alt="Screenshot 2022-11-08 153241" src="https://user-images.githubusercontent.com/90142988/200592275-7d0a2568-5e06-440f-aaea-928d695ebc29.png">

**Comment by debanjandhar12** [comment]
How do you think it should be implemented? Through logseq block tags (something like `#dont-show-breadcrum`) or through plugin settings?
