### ISSUE TITLE
Kanji furigana for Japanese with Anki support, {{furigana:Text}} field

### ISSUE THREAD

**Issue by DreamAfar** [debanjandhar12/logseq-anki-sync#129]
**Describe the solution you'd like**

Hi, thank you very much for making this Logseq plugin.
I'm learning Japanese with Logseq and Anki, and I'm having a problem with the logseq-anki-sync plugin.
Anki supports displaying Kanji zenkana in Japanese, just need to add a marker {{furigana:Text}} on the template field to display the zenkana correctly on the Japanese Kanji.

![image](https://user-images.githubusercontent.com/69999980/202632202-258ff1c4-d2cc-4b2a-81db-a8f96cbfa03f.png)
![image](https://user-images.githubusercontent.com/69999980/202632262-bddb6b7c-cb3f-4671-8b5f-51bc90d6e9a6.png)

**Describe how it will help your workflow**

I tried to modify the template of logseq-anki-syn by changing the {{cloze:Text}} field to {{cloze:furigana:Text}}, and it can be recognized and displayed correctly.
But logseq-anki-sync overrides back to the default template on the next sync, causing it to fail.

**Describe alternatives you've considered**

I hope we can adapt to support the display of the Japanese zenkana template and keep the sync without overwriting the {{cloze:furigana:Text}} field.

**Comment by debanjandhar12** [comment]
Can you provide me the contents of the logseq block? (so I can play around with it when I implement the feat?)

**Comment by DreamAfar** [comment]
> Can you provide me the contents of the logseq block? (so I can play around with it when I implement the feat?)

Block text in Logseq
- Q: 日本[にほん]のアニメが 好[す]きですから、 日本語[にほんご]を 勉強[べんきょう]します。#card
  - A: 因為喜歡日本的卡通，〈所以〉要學日文。
  - （Because I like Japanese cartoons, I want to learn Japanese.）
  - 「から」前面是原因理由，所以學日文的原因是因為喜歡日本的卡通。

![image](https://user-images.githubusercontent.com/69999980/202642957-03a3af27-8bf4-4fbd-8ee4-571eea204038.png)

Show in Anki
![image](https://user-images.githubusercontent.com/69999980/202644419-0aa07d55-e0f5-48cd-a39e-be2b1574ba33.png)
![image](https://user-images.githubusercontent.com/69999980/202644470-22c37898-5705-47ce-acc8-e9282ead593a.png)


By the way, the default font display may be appropriate for English, but for Japanese and Chinese, the default font size display is a bit small.

If possible, in Logseq's logseq-anki-sync advanced settings, add settings to customize: the css font size display in Anki, whether the text field is kana (furigana) for Japanese kanji, etc.
(Or preset a CSS template to easily modify the display of fonts such as text without moving other settings.)


Thank you for everything you do!

**Comment by debanjandhar12** [comment]
> > Can you provide me the contents of the logseq block? (so I can play around with it when I implement the feat?)
> 
> Block text in Logseq
> 
>     * Q: 日本[にほん]のアニメが 好[す]きですから、 日本語[にほんご]を 勉強[べんきょう]します。#card
>       
>       * A: 因為喜歡日本的卡通，〈所以〉要學日文。
>       * （Because I like Japanese cartoons, I want to learn Japanese.）
>       * 「から」前面是原因理由，所以學日文的原因是因為喜歡日本的卡通。
> 
> 
> ![image](https://user-images.githubusercontent.com/69999980/202642957-03a3af27-8bf4-4fbd-8ee4-571eea204038.png)
> 
> Show in Anki ![image](https://user-images.githubusercontent.com/69999980/202644419-0aa07d55-e0f5-48cd-a39e-be2b1574ba33.png) ![image](https://user-images.githubusercontent.com/69999980/202644470-22c37898-5705-47ce-acc8-e9282ead593a.png)
> 
> By the way, the default font display may be appropriate for English, but for Japanese and Chinese, the default font size display is a bit small.
> 
> If possible, in Logseq's logseq-anki-sync advanced settings, add settings to customize: the css font size display in Anki, whether the text field is kana (furigana) for Japanese kanji, etc. (Or preset a CSS template to easily modify the display of fonts such as text without moving other settings.)
> 
> Thank you for everything you do!

It is already possible to add css to the cards. See https://github.com/debanjandhar12/logseq-anki-sync/discussions/118

**Comment by DreamAfar** [comment]
> > > Can you provide me the contents of the logseq block? (so I can play around with it when I implement the feat?)
> > 
> > 
> > Block text in Logseq
> > ```
> > * Q: 日本[にほん]のアニメが 好[す]きですから、 日本語[にほんご]を 勉強[べんきょう]します。#card
> >   
> >   * A: 因為喜歡日本的卡通，〈所以〉要學日文。
> >   * （Because I like Japanese cartoons, I want to learn Japanese.）
> >   * 「から」前面是原因理由，所以學日文的原因是因為喜歡日本的卡通。
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ![image](https://user-images.githubusercontent.com/69999980/202642957-03a3af27-8bf4-4fbd-8ee4-571eea204038.png)
> > Show in Anki ![image](https://user-images.githubusercontent.com/69999980/202644419-0aa07d55-e0f5-48cd-a39e-be2b1574ba33.png) ![image](https://user-images.githubusercontent.com/69999980/202644470-22c37898-5705-47ce-acc8-e9282ead593a.png)
> > By the way, the default font display may be appropriate for English, but for Japanese and Chinese, the default font size display is a bit small.
> > If possible, in Logseq's logseq-anki-sync advanced settings, add settings to customize: the css font size display in Anki, whether the text field is kana (furigana) for Japanese kanji, etc. (Or preset a CSS template to easily modify the display of fonts such as text without moving other settings.)
> > Thank you for everything you do!
> 
> It is already possible to add css to the cards. See #118

Ok, I see, I have adjusted the CSS style according to my needs, thanks
