### ISSUE TITLE
change color scheme to fit night mode

### ISSUE THREAD

**Issue by howarddo2208** [debanjandhar12/logseq-anki-sync#131]
**Describe the solution you'd like**

The text color of cards in dark mode is unusable in some cases, especially for PDF annotations

desktop screenshot:
![image](https://user-images.githubusercontent.com/62332195/204119697-66f3151b-0cef-4527-b1ce-f433a72c3fa1.png)

mobile screenshot:
![telegram-cloud-photo-size-5-6059985936403509841-y](https://user-images.githubusercontent.com/62332195/204119764-7f8a766a-9bf3-4e36-8754-055ece21c66b.jpg)

I would be much better if the color scheme to be optimized both light and dark mode

**Comment by debanjandhar12** [comment]
Fixed in v4.5.0
