### ISSUE TITLE
Are keyboard shortcuts possible?

### ISSUE THREAD

**Issue by Vitorvlv** [debanjandhar12/logseq-anki-sync#133]
**Describe the solution you'd like**
The hability to highlight a word and then press a shortcut so it will create cards out of it. 

**Describe how it will help your workflow**
I think it will make it quicker.

I've attached a short example of what I would like using the native CTRL + B shortcut. But instead of putting **** around the word it would put {{c1 }}, the next one would put {{c2 }} and so on... 

Is that possible?

[Gravação de tela de 2022-11-30 22-35-26.webm](https://user-images.githubusercontent.com/26132870/204944879-262f3706-eed6-4039-a4db-dbbc192132ac.webm)

**Comment by debanjandhar12** [comment]
You can use https://github.com/sethyuan/logseq-plugin-wrap for making such shortcuts.

**Comment by Vitorvlv** [comment]
Thank you!
