### ISSUE TITLE
Personalization of the Breadcrumb in Anki

### ISSUE THREAD

**Issue by JoaoAzzuz** [debanjandhar12/logseq-anki-sync#135]
**Describe the solution you'd like**
I want to change the size of the Breadcrumb in Anki and maybe change its font color to fit better with my background image. The latter is not that urgent, but the size of the breadcrumb is really small for my computer, as you can see in the image below. I would love to see more personalization features in this plugin.
![image](https://user-images.githubusercontent.com/120520522/207449473-d56d74b2-98c4-426b-8c74-03f62904ded9.png)

**Describe how it will help your workflow**
That would help with the aesthetic of my workflow and help me to see my cards better.

**Describe alternatives you've considered**
I tried to change de font-size of the main text of the cards in Anki and it worked. But I couldn't change the Breadcrumb characteristics in Anki, I don't know much about coding and programming. 
Thank you for the amazing plugin by the way!

**Comment by debanjandhar12** [comment]
You can add custom css (https://github.com/debanjandhar12/logseq-anki-sync/discussions/118):
```css
.breadcrumb2 {
   font-size:20px !important;
}
```
