### ISSUE TITLE
[Fr] image occlusion doesn’t show all clozer blocks in questions image

### ISSUE THREAD

**Issue by andrewcrook** [debanjandhar12/logseq-anki-sync#137]
**Describe the solution you'd like**

when multiple blank outs are used to generate image occlusion cards have an option that keeps all other blank clozers in the question image covered.

I am finding it difficult to explain so here is an example using a crude mockup ....

Example image with n clozer blocks and multiple clozer ids
So for example the 5th Anki card question would show

![image](https://user-images.githubusercontent.com/803618/210377360-b6b0c067-37cd-4414-aaf3-f30600c62a0b.png)

and its answer would be 

![image](https://user-images.githubusercontent.com/803618/210377877-cdc8ffa3-54ef-47fd-ad9a-a6335b1c294a.png)

the other cards would be simular each using their own clozer i.e 1,2,3,4 ..... 

**Describe how it will help your workflow**
Currently when you go through cards using cards with clozers you can see all the details in previous cards and your brain will remember them. Having this feature will not display the details until the correct card for a specific clozer is displayed and the answer shown to reveal it.

**Describe alternatives you've considered**
None

**Comment by debanjandhar12** [comment]
Will be released with next version.
