### ISSUE TITLE
[Fr] Is it possible to bump up number of clozers allowed in image occlusion ?

### ISSUE THREAD

**Issue by andrewcrook** [debanjandhar12/logseq-anki-sync#138]
Currently it is limited to 5.
I wonder if it could be increased to 10, 15 or 20?

**Comment by debanjandhar12** [comment]
Increased to 9. It will be available on next release.

**Comment by andrewcrook** [comment]
Thanks

**Comment by wuqui** [comment]
I would love to have even more, actually 🤓
