### ISSUE TITLE
[Fr] Hide occlusion block property in Logseq

### ISSUE THREAD

**Issue by andrewcrook** [debanjandhar12/logseq-anki-sync#139]
**Describe the solution you'd like**
To be able to hide the occlusion block property in Logseq

![image](https://user-images.githubusercontent.com/803618/210382940-3da1f35d-aef1-4992-8999-1956d89e3a5c.png)

**Describe how it will help your workflow**
option to hide occlusion blocks as an option in plugins settings.

**Describe alternatives you've considered**
was thinking if this could be done with CSS override?
However, I cannot find a selector combination just for the occlusion block

**Comment by andrewcrook** [comment]
**Describe alternatives you've considered**

Awesome UI Plugin 
Add occlusion to hide list

![image](https://user-images.githubusercontent.com/803618/210452673-8e040a69-5bb1-4860-9004-69cf1fa5a2e1.png)

page with occlusion
<img width="1188" alt="image" src="https://user-images.githubusercontent.com/803618/210452990-0eb7dd9c-3a01-4889-8003-3c571cea8e88.png">

click on area to see data
Unfortunately you have to reload the page to hide again.

**Comment by debanjandhar12** [comment]
> **Describe alternatives you've considered**
> 
> Awesome UI Plugin Add occlusion to hide list
> 
> ![image](https://user-images.githubusercontent.com/803618/210452673-8e040a69-5bb1-4860-9004-69cf1fa5a2e1.png)
> 
> page with occlusion <img alt="image" width="1188" src="https://user-images.githubusercontent.com/803618/210452990-0eb7dd9c-3a01-4889-8003-3c571cea8e88.png">
> 
> click on area to see data Unfortunately you have to reload the page to hide again.

I think you should report the bug to Awesome UI.

**Comment by debanjandhar12** [comment]
Also, other than Awesome UI, you can add the following line in config.edn:
`:block-hidden-properties #{:occlusion}`

This would hide the occlusion property in both view and editor modes.

**Comment by andrewcrook** [comment]
> Also, other than Awesome UI, you can alternatively add the following line in config.edn: `:block-hidden-properties #{:occlusion}`
> 
> This would hide the occlusion property in both view and editor modes.

That is a better solution thanks.
However, I think it would be good to have an option to add this in the plugins settings.

**Comment by debanjandhar12** [comment]
Added in v5.5.0
