### ISSUE TITLE
Picture and multiline support in the extra field

### ISSUE THREAD

**Issue by Futur3r** [debanjandhar12/logseq-anki-sync#145]
**Describe the solution you'd like**
The ability to put picture or write on multiple lines in the extra field. 

**Describe how it will help your workflow**
I frequently put pictures, schemas, etc. in the extra field of my flashcards or I write on multiple lines to make the text a bit easier to read.
Right now, I can't put images with the plugin and if I do it in Anki, the extra field will get overwrited.

**Describe alternatives you've considered**
No alternatives, apart writing a concise sentence. Not really easy to do in the middle of a presentation.

**Comment by Futur3r** [comment]
For ideas, I'm good with putting something like `\n` in the text as value of the extra property, to indicate to the plugin to put a newline for example.
And for the pictures, I think Anki can take absolute path in HTML ?

**Comment by debanjandhar12** [comment]
Can you provide the source? 
I just tested and saw that something like this works:
```
extra:: ![image.png](../assets/image_1674829421173_0.png) Hello
Hello {{c1 World}}
```
Additionally, if you want to make multi-line extra filed, I suggest using org block syntax (it is usable in markdown mode):
```
Hello {{c1 World}}
#+BEGIN_EXTRA
I am extra 
multiline text.
#+END_EXTRA
```

**Comment by Futur3r** [comment]
I tested your code and figured out that it didn't work for me because I use a non-asset file as an image.
Works fine with asset files.

Noted for org mode for multiline.
Thanks !
