### ISSUE TITLE
Ability to add tags on Anki cards with a property

### ISSUE THREAD

**Issue by Futur3r** [debanjandhar12/logseq-anki-sync#147]
**Describe the solution you'd like**
I saw that tags of Anki cards are added with the hashtag syntax of logseq, but would it be possible to disable that and add tags via the tags:: property of Logseq with the same mechanism of the deck:: property (blocks of a page inherit the page properties)  .
The switch could be made as an option in the settings.

**Describe how it will help your workflow**
When I add Logseq links as hashtags, it's not for Anki and it pollutes my Anki tags.
For flashcards I add simple tags for a whole Logseq Notes, so the mechanism of the deck:: property is better for me.

**Comment by thiswillbeyourgithub** [comment]
Also, I noticed that you can specify `deck:: some::deck` as a property of a parent block (so all the cards created as children of its childrens (!) are in the same deck) but you can't do that with `tags::` property.

But you can set the tags in the children directly. I think it would be a great improvement if we could set the `tags::` in the parents just like for deck.

My use case is that I'm a medical student with lots of decks and lots of nested cards.

**Comment by thiswillbeyourgithub** [comment]
Sorry for the multiple message, don't take it as harassment pleaee :) I'm offering a $20 bounty for the tag feature suggested in #117

**Comment by thiswillbeyourgithub** [comment]
> No need to apologize. I should be the one apologizing for not replying earlier.

FOSS is good only when it works for the author's pace :)

Yes, the FR is to have cards be tagged with any tag in the "above" hierarchy. Basically like the decks property but where they are all taken into accounts instead of the "closest property" (as is the case for decks).

**Comment by debanjandhar12** [comment]
Added in v4.6.1

**Comment by thiswillbeyourgithub** [comment]
Thanks a lot a lot a lot, it's really great. I do notice however that if I have the following structure : 
```
- # some title
  tags:: psychiatry
    - some other stuff
      tags:: psychiatry::antipsychotics
```

Then the resulting card will have 2 tags `psychiatry psychyatry::antipsychotics` instead of just `psychiatry::antipsychotics`. Given how anki handles the tags I think it would be best to only include the tags that are not already implied as it will otherwise quickly clutter my collection.

What do you think?

**Comment by thiswillbeyourgithub** [comment]
Also found a bug: the addon only works with "tags" and not "Tags" even though logseq is case insensitive regarding properties. This is problematic because if you have `Tags:: something`, and turn it into `tags:: something` Logseq will ignore the change.

Expected behavior is then to fetch tags properties case insensitively.

**Comment by debanjandhar12** [comment]
> Thanks a lot a lot a lot, it's really great. I do notice however that if I have the following structure :
> 
> ```
> - # some title
>   tags:: psychiatry
>     - some other stuff
>       tags:: psychiatry::antipsychotics
> ```
> 
> Then the resulting card will have 2 tags `psychiatry psychyatry::antipsychotics` instead of just `psychiatry::antipsychotics`. Given how anki handles the tags I think it would be best to only include the tags that are not already implied as it will otherwise quickly clutter my collection.
> 
> What do you think?

Sorry, can you create a new issue for it? I will take a look at it sometime around Friday. It should be fairly easy to do with hash maps.



> Also found a bug: the addon only works with "tags" and not "Tags" even though logseq is case insensitive regarding properties. This is problematic because if you have `Tags:: something`, and turn it into `tags:: something` Logseq will ignore the change.
> 
> Expected behavior is then to fetch tags properties case insensitively.
