### ISSUE TITLE
Limit to one child down in #card #incremental type of flashcards

### ISSUE THREAD

**Issue by Futur3r** [debanjandhar12/logseq-anki-sync#148]
**Describe the bug**
When I make 'list' flashcards with #card #incremental when the children blocks have children themselves, the plugin makes cards like this:

-  types de formation de précipitation #card #incremental
   - {{c1:: précipitation frontale
       - TODO ajouter images de "différentes possibilités de formations ..."
      }}

**Steps to Reproduce:**
Create a card with #card #incremental with 2 or 3 'layers' of children blocks down.

**Expected behavior**
The plugin should create the flashcard with only the direct children (one children down) of the block with #card #incremental.

**Device Information (please complete the following information):**
 - OS with version: Linux Mint 21
 - Logseq Anki Sync Plugin Version: 4.2.0
 - Anki Version: 2.1.54
 - Logseq Version: 0.8.10

**Comment by Dunrar** [comment]
Isn't the `#card #incremental #depth-n` option what you need?

**Comment by Futur3r** [comment]
Yes, it is. Sorry for the issue.
