### ISSUE TITLE
Code close works with ~~~ but not ``` in Anki. Ideally have clozes and fenced code blocks in Logseq and Anki.

### ISSUE THREAD

**Issue by kieranlal** [debanjandhar12/logseq-anki-sync#149]
**Describe the bug**
Inconsistent code cloze rendering in Anki and Logseq between four types of code markup in Logseq:
[fenced code blocks with three tildes](https://www.markdownguide.org/extended-syntax/#fenced-code-blocks)
Doesn't render cloze in Logseq but does in Anki
```
~~~python
code {{cloze tildes}}
~~~
#card
```

or this code that doesn't render cloze in Logseq, but does in Anki.
```
~~~python
one_to_ten = [{{cloze  c i for i in range(1, 11)}}]
print(type(one_to_ten[0]))#<class 'int'> 
centre_text(one_to_ten) #[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
print(str(one_to_ten)[1]) #1
centre_text(str(one_to_ten)) #[1, 2, 3, 4, 5, 6, 7, 8, 9, 10] type str
close: {{cloze testme}} 
~~~
#card
```
[Fenced code blocks](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#fenced-code-blocks)
````
```python
code {{cloze backticks}}
```
#card
````

Renders clozes in both Logseq and Anki but not as fenced code block in Logseq. 
```
``python
code {{cloze two backticks}}
``
#card
```

Renders clozes in both Logseq and Anki but not a numbered fenced code block.
```
`python
code {{cloze one backtick}}
`
#card
```
replacecloze
```
replacecloze:: " 'a^{2}+b^{2}', /(c\^2|c )/gi "
~~~Python
The Pythagorean theorem is:
$$c =\sqrt{ a^{2}+b^{2} }$$
$$c^2= a^{2}+b^{2}$$
~~~
#card
```

**Steps to Reproduce:**
1. Paste the four code blocks above in their own blocks in a Logseq page.
2. Sync with logseq-anki-sync and get four cards in Anki
3. Three tildes works, two backticks works and looks like code, one backtick works and looks like text.  Three backticks doesn't work.
4. The markdown for three tildes code block and three backticks code block is almost identical except the cloze is not rendered with backticks in Anki.
5. If you try to use replacecloze with a fenced code block in logseq that doesn't work inside Anki. 

**Expected behavior**
Expect clozes to be rendered in Anki cards across all four types of code blocks. Ideally clozes would also be rendered inside fenced code blocks(numbered) in Logseq.  A supported consistent formatting could be documented and recommended. 
```
<ul class="children-list"><li class="children">
      <pre><code data-lang="python" class="python hljs">code {{cloze backticks}}
</code></pre>
      <span><a class="tag" href="logseq://graph/Documents?page=card">card</a></span>
    </li>
</ul>
```

**Developer console screenshot:**
Please add a screenshot of the error in logseq's developer console if applicable. Logseq's developer console can be accessed by pressing `Ctrl + Shift + I`.

**Device Information (please complete the following information):**
 - OS with version: [MacOS Ventura 13.1] 
 - Logseq Anki Sync Plugin Version: [4.2.0]
 - Anki Version: [Version ⁨2.1.54 (b6a7760c)⁩]
 - AnkiConnect Addon Version: ["name": "AnkiConnect", "mod": 1663546263,]
 - Logseq Version: [Version 0.8.16 (0.8.16)]
 
<img width="853" alt="Logseq-four-markdown-types-code-blocks" src="https://user-images.githubusercontent.com/30537530/215248413-ddb6caf3-5965-43e0-8fcc-a7b86e845380.png">

**Comment by debanjandhar12** [comment]
Thanks for the bug report. I wasn't aware of the `~~~` syntax for code blocks.

Now, coming to the point, it is not possible to support clozes inside codeblocks in Logseq (macros inside codeblocks is not possible). Hence, it was disabled in backtick codeblock.

The documented way to create clozes inside things like math and codeblocks is to use `replacecloze` prop.
- ```
  replacecloze:: " /print/gi "
  ~~~python
  print("Hello")
  print("World")
  ~~~
  ```

I think it would make sense to disable it inside `~~~` codeblocks as well.
---
Also, can you please clarify about the numbered fenced code block part?

**Comment by kieranlal** [comment]
Thanks for the quick and detailed response.

Hi, by numbered fenced code block I mean the block that has numbers on the left margin for seeing what line of code you are addressing. See in the image below. 
<img width="787" alt="replace-cloze-logseq-doesnot-render" src="https://user-images.githubusercontent.com/30537530/215278736-8be0b99a-965e-4325-94fd-d85b07d5bb26.png">

Thank-you
