### ISSUE TITLE
Can I just tag a middle block as a card and not include the parent block in the generated anki card?

### ISSUE THREAD

**Issue by predawnang** [debanjandhar12/logseq-anki-sync#152]
Hi, there.

I want to know is there a way to exclude the parent block (like the first two block in the picture1 below) in the anki card. 
<img width="609" alt="image" src="https://user-images.githubusercontent.com/37857978/215819045-5cc9fa58-3b37-4225-ab73-f77a6aeaa397.png">
so that i can achieve something like the picture below
<img width="735" alt="image" src="https://user-images.githubusercontent.com/37857978/215819833-02b8f60f-043d-4eb2-8bcd-005a31cba26a.png">

thank you

**Comment by debanjandhar12** [comment]
try disabling the "Include parent content in cards" checkbox in plugin settings

**Comment by predawnang** [comment]
> 
thank you so much, and awesome plugin.
