### ISSUE TITLE
Image Occlusion card doesn't show on AnkiMobile

### ISSUE THREAD

**Issue by junyounglees** [debanjandhar12/logseq-anki-sync#153]
When you make an image occlusion card, it doesn't show on AnkiMobile (iOS). You can see only bubble and arrow buttons on front and back of the card. In "Preview" of card template menu on AnkiMobile, frontside has an original size image occlusion while backside has resized image as usual.

**Describe the solution you'd like**
I want image occlusion card to show on AnkiMobile with proper image-resizing.

**Describe how it will help your workflow**
Seamless integration between desktop Anki and AnkiMobile.

**Comment by debanjandhar12** [comment]
It seems like a bug.

Can you please provide some more information:
- The contents of the block generating the image occlusion. (I am interested in the image tag)
- AnkiMobile Version

**Comment by junyounglees** [comment]
- I'm using the latest version of AnkiMobile (2.0.89) and Desktop (2.1.57)
- The contents of the block is like below:

<ul class="children-list"><li class="children">
      <span><img src="CleanShot_2023-02-13_at_23.03.48@2x_1676297033116_0.jpg" title="CleanShot 2023-02-13 at 23.03.48@2x.jpg">
        <br>
<div class="hidden">
        {{c1:: ::<span id="c1"></span>}}
        <div id="imgToOcclusionArrHashMap">{"../assets/CleanShot_2023-02-13_at_23.03.48@2x_1676297033116_0.jpg":[{"left":231.67905500595757,"top":153.98,"width":107.36,"height":69.96,"angle":0,"cId":1}]}</div>
        <img id="localImgBasePath" src="_logseq_anki_sync.css">
        </div></span>
    </li></ul>

- below is what I see on my AnkiMobile
<img width="414" alt="image" src="https://user-images.githubusercontent.com/11092098/218480400-e9904bef-0665-4d2f-9373-e85dffa7e1d1.png">

- but If I tap flip button on 'Preview' mode, I get the frontside like below.
![IMG_9267](https://user-images.githubusercontent.com/11092098/218480748-36c01214-97df-4e85-a901-632e402c6738.png)
