### ISSUE TITLE
Card template is reset every time Logseq to Anki Sync is used.

### ISSUE THREAD

**Issue by Vitorvlv** [debanjandhar12/logseq-anki-sync#157]
Hi! Whatever change I made to the cards template are reset when the Sync is done again.

This is an issue because I'm using a custom scheduler for anki ([FSRS](https://github.com/open-spaced-repetition/fsrs4anki)) need to do a modification to all my cards front-templates to add this:

```
<div id=deck deck_name="{{Deck}}"></div>
```
But this is always erased when I sync logseq to anki. 

Is there any way I can keep that modification ?

**Comment by debanjandhar12** [comment]
At the moment, it is not possible without modifying the source code of this plugin. 

I can add it for you in the code of next release if you want. I have been quite interested in [FSRS](https://github.com/open-spaced-repetition/fsrs4anki) as well.

Just to clarify once again, only adding the `<div id=deck deck_name="{{Deck}}"></div>` is enough right?

**Comment by Vitorvlv** [comment]
> I can add it for you in the code of next release if you want.

That would be much appreciated, thank you!!

> only adding the <div id=deck deck_name="{{Deck}}"></div> is enough right?

Yes it's enough, this is needed if you want to do per-deck optimization/settings.

If it wouldn't be too much trouble, may I also ask you to add this one:

```
<div id=tags tags_name="{{Tags}}"></div>
```

This is needed if you want to do parameters for a specific tag, instead of decks. My workflow is heavily dependant on tags, so this would be a great help. 

Per this issue: https://github.com/open-spaced-repetition/fsrs4anki/issues/106

It's not an officially supported method, so it would be understandable if you didn't want to add it, but it does works great, and if people are not using it it's not going to interfere in anything.
