### ISSUE TITLE
make a block without subblock to card

### ISSUE THREAD

**Issue by chs33** [debanjandhar12/logseq-anki-sync#16]
if I transform single block **without any cloze content and without any subblock** to a card, looks like anki will try to identify it as a cloze card type

card in logseq:
![image](https://user-images.githubusercontent.com/16418270/149648922-362694b7-816f-4bb3-a95e-7c3dbb728818.png)

in anki:
![image](https://user-images.githubusercontent.com/16418270/149648977-0be5029d-6353-4944-94ae-6952f2249cf1.png)

since I didnt have any cloze content in my block anki will showed up as 
![image](https://user-images.githubusercontent.com/16418270/149425847-0a69209e-1d84-413b-a35a-bc269530f150.png)

I understand it is odd to have a card without neither back side nor cloze content. And it maybe just the way your plugin is designed, but in anycase i am wondering if it is possible to make anki to treat card in case like this a basic front-back card type? (I could work around it by making an artificial empty subblock, that would make the notes in logseq looks ugly though)

**Comment by debanjandhar12** [comment]
Thanks. I will take a look at it later this month.

**Comment by chs33** [comment]
After this fix, plain text block (meaning it doesn't contain cloze content) without subblock is ignored by the plugin and won't export to anki. Will you make it able to export such block to anki card in future release? 
(I could work around it by making an artificial empty subblock, that would make the notes in logseq looks ugly though)

**Comment by chs33** [comment]
Follow up on this, with current version, the card without child block is ignored by the plugin, and won't showed up. The ideal behavior in my mind would be it still being recognized by the plugin as a basic card type, with no answer/empty answer

![image](https://user-images.githubusercontent.com/16418270/174683936-64df2239-075d-49a4-964d-ae0d2777bfe6.png)
![image](https://user-images.githubusercontent.com/16418270/174683976-9504afb6-c07d-4c17-bcf9-a0da1d33f78e.png)

**Comment by debanjandhar12** [comment]
> Follow up on this, with current version, the card without child block is ignored by the plugin, and won't showed up. The ideal behavior in my mind would be it still being recognized by the plugin as a basic card type, with no answer/empty answer
> 
> ![image](https://user-images.githubusercontent.com/16418270/174683936-64df2239-075d-49a4-964d-ae0d2777bfe6.png) ![image](https://user-images.githubusercontent.com/16418270/174683976-9504afb6-c07d-4c17-bcf9-a0da1d33f78e.png)

Are you sure you want this? This will cause "no cloze in card" message from anki during practice. Anki doesn't like notes that do not have any cloze.

**Comment by chs33** [comment]
> > After this fix, plain text block (meaning it doesn't contain cloze content) without subblock is ignored by the plugin and won't export to anki. Will you make it able to export such block to anki card in future release? (I could work around it by making an artificial empty subblock, that would make the notes in logseq looks ugly though)
> 
> > Follow up on this, with current version, the card without child block is ignored by the plugin, and won't showed up. The ideal behavior in my mind would be it still being recognized by the plugin as a basic card type, with no answer/empty answer
> > ![image](https://user-images.githubusercontent.com/16418270/174683936-64df2239-075d-49a4-964d-ae0d2777bfe6.png) ![image](https://user-images.githubusercontent.com/16418270/174683976-9504afb6-c07d-4c17-bcf9-a0da1d33f78e.png)
> 
> Are you sure you want this? This will cause "no cloze in card" message from anki during practice. Anki doesn't like notes that do not have any cloze.

The behavior in my mind is to make it display the card content (as question) and when clicking "show answer" it shows empty. It is like the you make a card of Anki's default "Basic" type, type in your question in the "Front" and leave the "Back" empty like this:
![image](https://user-images.githubusercontent.com/16418270/178161582-b2a718a2-6238-4d2b-ba33-7f76dbcbfbe9.png)

it is not regarded as cloze type at first place. Though I am not sure how feasible it is to achieve it in plugin, from front template of logseq-notesModel looks like everything is regarded as some sort of cloze

**Comment by debanjandhar12** [comment]
> it is not regarded as cloze type at first place. Though I am not sure how feasible it is to achieve it in plugin, from front template of logseq-notesModel looks like everything is regarded as some sort of cloze

Yep, every type is actually a cloze. However, since it is possible to execute js inside anki, almost anything is possible. 
NB: added it and should be included in next version.
