### ISSUE TITLE
Top part not readable in dark mode

### ISSUE THREAD

**Issue by Vitorvlv** [debanjandhar12/logseq-anki-sync#161]
![image](https://user-images.githubusercontent.com/26132870/221880058-2bef8daf-73fa-4dae-86be-6e01cf0ee3f8.png)

anything I can add in the styling section to make it better?

**Comment by wuqui** [comment]
I second this. It’s a small detail, but very bad in terms of usability.

Thanks for this cool plugin btw! 🙂

**Comment by debanjandhar12** [comment]
Fixed in v4.5.0
