### ISSUE TITLE
show the card being newly created and the card being deleted at sync time

### ISSUE THREAD

**Issue by chs33** [debanjandhar12/logseq-anki-sync#165]
Right now the plugin show message about the count of the newly created and deleted card every time you sync with anki like following,

![image](https://user-images.githubusercontent.com/16418270/227748035-ffcf728d-9b00-43fa-81e6-0eaac8a32531.png)

I think it might be more informative to have a way to provide some sort of glance of the what are the cards being deleted/created to make sure that they are as expected.

**Comment by debanjandhar12** [comment]
It is not possible to view the cards to be deleted in the new version.

**Comment by debanjandhar12** [comment]
now*
