### ISSUE TITLE
Background of `extra:: ...` is always light-mode

### ISSUE THREAD

**Issue by raresteposu** [debanjandhar12/logseq-anki-sync#167]
**Describe the bug**
Background of the `extra:: ...` property doesn't sync with dark mode, although text remains white, so it becomes unreadable (white text on white background)

**Steps to Reproduce:**
1. Create a Logseq card with the `extra::` property, as described in the documentation [here](https://github.com/debanjandhar12/logseq-anki-sync/discussions/92)
2. View the card in Anki, with dark mode enabled

**Expected behavior**
Text should be readable. Either darkening the background (preferable) or darkening the text (not preferable, as it will not be true dark mode)

**Device Information (please complete the following information):**
 - OS with version: [e.g. Windows 11 Home 21H2] 
 - Anki Version: 2.1.55
 - AnkiConnect Addon Version: 2.1.0
 - Logseq Version: 0.9.1

---

![grafik](https://user-images.githubusercontent.com/37986097/230434172-1517a137-f63b-43dd-91e8-65447073b379.png)
![grafik](https://user-images.githubusercontent.com/37986097/230434265-2d23ab8a-8d78-45a1-aa51-a607a53c126b.png)

**Comment by debanjandhar12** [comment]
Fixed in v4.5.0
