### ISSUE TITLE
cloze card with/without "#card"

### ISSUE THREAD

**Issue by chs33** [debanjandhar12/logseq-anki-sync#17]
looks like right now the correct way to make cloze card is to make cloze without adding "#card". 

It would be more consistent if I can add "#card" so that my card page has all the card in linked reference section.

and FYI right now if add "#card" at the end of a cloze card in logseq, in anki it will create TWO cards which is not desired. and one can work properly the other don't.

in logseq:
![image](https://user-images.githubusercontent.com/16418270/149647290-bf1dc718-7cca-45c0-8f6b-1e8f7fde43e3.png)

in anki it generate two cards:

this one doesn't work as their is no c1 in it 
![image](https://user-images.githubusercontent.com/16418270/149647303-579bb015-2a42-481b-8027-45b65d5f20f0.png)

this one works
![image](https://user-images.githubusercontent.com/16418270/149647323-961821df-0732-4c5e-9031-428f4b80769d.png)

**Comment by debanjandhar12** [comment]
The plugin will no longer create a note for `#card blocks` that has no children and are not reversed or bidirectional.
