### ISSUE TITLE
支持logseq中的markdown链接的本地图片。（重点：本地图片）

### ISSUE THREAD

**Issue by leommjj** [debanjandhar12/logseq-anki-sync#171]
希望可以在anki中同步logseq的本地图片

**Comment by debanjandhar12** [comment]
Replying based on google translate:
![image](https://user-images.githubusercontent.com/49021233/235488044-30da0adb-ae2c-4c9a-8540-d25a385ad1d6.png)

The plugin already supports local logseq images. Please re-open the issue with dev console screenshot in case the plugin is failing to sync images.
