### ISSUE TITLE
链接导出错误

### ISSUE THREAD

**Issue by leommjj** [debanjandhar12/logseq-anki-sync#172]
![CCCGIQL5(14)_KVHWA~U)$6](https://user-images.githubusercontent.com/101880110/235310728-bc1ef5a6-d74b-4de9-9903-aa7fdc698ed2.png)
### logseq中的代码：
信息社会与复杂的社交
>语言：伟大社会的基础 [218](bookxnotepro://opennote/?nb={e2de0388-155e-41d6-8d6a-b08e43cd5acc}&book=ecf8ff1ef5e2ea9b1c334cea762bf005&page=217&x=306&y=175&id=46&uuid=1c52bd8a59bb169993a137c619d4fffa)

**Comment by leecobaby** [comment]
你用中文人家可能看不懂，同时你的问题没有表示清楚，是什么场景下做了什么发生了什么，理想的结果是什么。
我试了下将本地图片移入 logseq #card 子快，并导入 anki 是可以正常显示的。

**Comment by leommjj** [comment]
![image](https://github.com/debanjandhar12/logseq-anki-sync/assets/101880110/910844f3-e7e8-4f4b-bbfc-7abc1d0ce6fd)
注意看这两个链接的区别：少了两个//
另外这个问题，之前也有人翻译过了https://github.com/debanjandhar12/logseq-anki-sync/issues/74#issue-1264132367

**Comment by debanjandhar12** [comment]
Sorry, I do not know Chinese. From what I understand from Google translate, you are talking about the bug with url conversation, right?

It has been reported before as well and I plan to take a look at it this weekend.
