### ISSUE TITLE
Color of cloze content in dark mode in v4.5.0

### ISSUE THREAD

**Issue by mtrzcinski98** [debanjandhar12/logseq-anki-sync#174]
Hello,

it seems to me that in the newest version of this plugin color of the cloze content went from lightblue to blue. As blue color in dark mode is less pleasant to read (at least to me), I'd like to ask if there is a chance to change the color of cloze content back to lightblue?

<img width="992" alt="image" src="https://user-images.githubusercontent.com/128076122/235771489-a1c98569-400c-4c0a-85c5-0852e3b17183.png">

**Comment by debanjandhar12** [comment]
Thank you, 
I will add the fix inside the style.css in the next version.
