### ISSUE TITLE
The logseq export for Anki links is missing "://".

### ISSUE THREAD

**Issue by keen0309** [debanjandhar12/logseq-anki-sync#176]
Please see the content in the picture. In logseq, after "booxnotepro", there is "//", and sending it to Anki makes it disappear.
![image](https://user-images.githubusercontent.com/103982843/236419423-ecac38a3-e432-4389-b547-1fcf29dd48f5.png)

**Comment by debanjandhar12** [comment]
Duplicate of https://github.com/debanjandhar12/logseq-anki-sync/issues/74. Will be fixed in V4.6.0.
