### ISSUE TITLE
multiple cloze in one card

### ISSUE THREAD

**Issue by chs33** [debanjandhar12/logseq-anki-sync#18]
if a card with multiple cloze is made in logseq, in anki it will be tested each cloze one at a time with other cloze revealed. I am wondering if it is feasible to make it an option to config them such that they are hided and being tested all at once. 

Effectively it is like changing everything to c1 cloze
![image](https://user-images.githubusercontent.com/16418270/149649171-03ec9f37-2f83-4fd4-8a78-0627766bdd1b.png)

whereas right now it is:
![image](https://user-images.githubusercontent.com/16418270/149649135-7609c04a-50c2-462c-822d-4f6bcd6d7aa1.png)

**Comment by debanjandhar12** [comment]
Currently you can use replacecloze property to achieve it.

```md
replacecloze:: " (first cloze|second cloze)/g "
```

**Comment by chs33** [comment]
> Currently you can use replacecloze property to achieve it.
> 
> ```lisp
> replacecloze:: " (first cloze|second cloze)/g "
> ```

had this but didn't show up in anki
![image](https://user-images.githubusercontent.com/16418270/149685451-0e053163-2871-4b58-85bd-e955abc7dadd.png)

**Comment by debanjandhar12** [comment]
Ah, sry i missed a slash. Try this:
```md
replacecloze:: " /(first cloze|second cloze)/g "
test first cloze second cloze
```
