### ISSUE TITLE
The text color of the confirmation dialog is not compatible with the dark theme.

### ISSUE THREAD

**Issue by leecobaby** [debanjandhar12/logseq-anki-sync#181]
**Describe the bug**
The text color of the confirmation dialog is not compatible with the dark theme. 
In dark theme, make the text color gray.

**Steps to Reproduce:**
1. Go to any page
2. Click on “Start Logsql to Anki sync” button
**3. See the text color of the confirmation dialog is not compatible with the dark theme.**

**Device Information (please complete the following information):**
 - OS with version: MacOS 13.0 
 - Logseq Anki Sync Plugin Version: 4.5.1
 - Anki Version:⁨ 2.1.54
 - Logseq Version: 0.8.16

<img width="669" alt="截屏2023-05-11 17 43 44" src="https://github.com/debanjandhar12/logseq-anki-sync/assets/48404687/fa08f3b2-089c-46fb-ab61-24c5f5d68cb0">

**Comment by debanjandhar12** [comment]
Thanks for the PR again. I have merged it and pushed a release.

**Comment by leecobaby** [comment]
> Thanks for the PR again. I have merged it and pushed a release.

Thank you also for creating such a great plugin; it has made a significant impact on my life.
Good luck bro.
