### ISSUE TITLE
tags by property should not duplicate tags that are implied

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [debanjandhar12/logseq-anki-sync#185]
I do notice however that if I have the following structure :

- # some title
  tags:: psychiatry
    - some other stuff
      tags:: psychiatry::antipsychotics

Then the resulting card will have 2 tags psychiatry psychyatry::antipsychotics instead of just psychiatry::antipsychotics. Given how anki handles the tags I think it would be best to only include the tags that are not already implied as it will otherwise quickly clutter my collection.

Related to #147

**Comment by debanjandhar12** [comment]
Solved. Will make a release in two days.

**Comment by thiswillbeyourgithub** [comment]
Thank you very much. You will receive your $20 bounty shortly. Have a nice day!

**Comment by thiswillbeyourgithub** [comment]
Hi! I'm very very sorry for the delay but just wanted to tell you that the bounty was payed today. Thanks again a lot!
