### ISSUE TITLE
Tags for all cards on a page

### ISSUE THREAD

**Issue by navakelvin** [debanjandhar12/logseq-anki-sync#194]
Excuse me sir. Just like "deck::" puts all the cards into a deck. "tag::" or "tags::" can assign tags to all cards created from a page?

![image](https://github.com/debanjandhar12/logseq-anki-sync/assets/77164639/a6ad93a8-d621-4c2d-9793-f3763b638f9a)

Is it a feature already developed in the plugin? If not, consider it as a new one please.

**In short: Add tags to all cards from page properties, allowing additional individual tags to be added per block.**

Thank you.

**Comment by thiswillbeyourgithub** [comment]
A very recent update include tags for all tags properties in parents of the block. Have you checked?

**Comment by navakelvin** [comment]
> A very recent update include tags for all tags properties in parents of the block. Have you checked?

Thank you! I see it now.
