### ISSUE TITLE
Need better handling of image occlusion created from pdf excerpts

### ISSUE THREAD

**Issue by Feliconut** [debanjandhar12/logseq-anki-sync#196]
**Describe the bug**
Image occlusion can be created from pdf excerpts in logseq. To make this happen, first create an excerpt in some `test.pdf` in logeq (specifically by using the "box" tool), then create a block reference to that excerpt in some page, say `page.md`. Then, inside `page.md`, create an image occlusion from that block in `page.md`.

The plugin first prompts the user to select the image file. After selecting the only available image file, the occlusion editor functions correctly, and also syncs correctly to anki.

**The problem is**, after editing the pdf excerpt in pdf (by dragging the excerpt box at its edges), the image occlusion will fail. Although the base64-encoded occlusion information is still in the block, the occlusion is ignored in the occlusion editor, and cannot be recovered in any way.

**The reason of the problem is**, although editing the pdf excerpt does not change its block-uuid, the id of the underlying image gets changed each time the excerpt is edited. This can be verified by inspecting the `./assets/<file-name>.edn` (in this case, `assets/test.edn`), which contains all highlight information for `test.pdf`, and noting that the associated image id is updated every time any edition is made to the excerpt. 

After inspecting the source code, I found that the `logseq-anki-sync` plugin associates each occlusion explicitly with the image file. This make it incapable of dealing with the situation where the underlying image is replaced.

**Steps to Reproduce:**
1. Open a pdf in logseq
2.  Create a box annotation
3. Go to the block for that box annotation
4. Create an image occlusion from the block
5. Check that plugin works correctly
6. Make an edition of that annotation by dragging its edge
7. Check that the occlusion fails

**Expected behavior**
It is suggested that one of the following change be made:
1. Make the occlusion point to both the block-uuid and the image file. When there is contradicting match, direct link to image file is prioritized and the block-uuid is updated to resolve the contradiction.
2. Demand explicit match of the image file only when there are multiple images in a same block. If only one image is found in the block, the occlusion is directly applied to that block.

Additionally, the following changes are suggested to better handle the editions made to pdf excerpts:
1. For pdf excerpts, store the position of the upper-left corner of the excerpt in the occlusion json data. The position of the excerpt can be read from the `assets/<file-name>.edn` file under the corresponding `uuid`. This allows dynamic update of the occlusion position in case the pdf excerpt is updated. In this way, editing the pdf excerpt will not impact the "absolute position" of the occlusion in the pdf document.

**Developer console screenshot:**
Please add a screenshot of the error in logseq's developer console if applicable. Logseq's developer console can be accessed by pressing `Ctrl + Shift + I`.
<img width="856" alt="Screenshot 2023-06-17 at 23 37 56" src="https://github.com/debanjandhar12/logseq-anki-sync/assets/33282070/47d0455b-4b6d-4088-9678-27dd017cf8c8">

**Device Information (please complete the following information):**
 - OS with version: [macOS 13.4] 
 - Logseq Anki Sync Plugin Version: [4.6.6]
 - Anki Version: [2.1.65]
 - AnkiConnect Addon Version: [23.4.11.0]
 - Logseq Version: [e.g. 0.9.9]

**Comment by Feliconut** [comment]
I would be helpful if the maintainer of the plugin can comment on which suggested solution is preferred; after that I am willing to create a pull request that make the proposed changes.

**Comment by debanjandhar12** [comment]
I see. The image annotation asset url contains the block uuid and the highlight time-stamp. The highlight time-stamp changes when the annotation is resized.

Let me think a bit on which approach is better. I will get back to you by tomorrow.

**Comment by debanjandhar12** [comment]
I think using a third strategy that manages image annotations directly would work better. The idea is to update the imageOcclusionHashMap before performing operations. I've been working on this myself and you can find my progress here: https://github.com/debanjandhar12/logseq-anki-sync/tree/Issue_196

Can you please take a look and fix any issues that come up? I didn't get the time to test it properly.

**Comment by Feliconut** [comment]
Hello. I saw your new method `migrateOutdatedImages()`. I am not sure if it is finished, but it seems to me that the current version (commit 5500110c9a386f63b5d3ff506b900070389b6f93) is not producing expected behavior. When the pdf excerpt is edited, the `migrateOutdatedImages` function will fail to match any image and return an empty object.

In my view it is necessary to read `./assets/<pdf-file-name>.edn`, in order to match the annotation to the specific excerpt in the pdf file, instead of the image produced by that excerpt. 

To do that, we may also need to refactor the current code a little bit. Currently the `pdf-file-name` is treated as something static and used as key in `imgToOcclusionArrHashMap`. We might want to change `imgToOcclusionArrHashMap` to something like a list of objects, where each object represents a set of occlusions, and has `image-path` as its property.

What do you think of this?

**Comment by debanjandhar12** [comment]
> Hello. I saw your new method `migrateOutdatedImages()`. I am not sure if it is finished, but it seems to me that the current version (commit [5500110](https://github.com/debanjandhar12/logseq-anki-sync/commit/5500110c9a386f63b5d3ff506b900070389b6f93)) is not producing expected behavior. When the pdf excerpt is edited, the `migrateOutdatedImages` function will fail to match any image and return an empty object.
> 
> In my view it is necessary to read `./assets/<pdf-file-name>.edn`, in order to match the annotation to the specific excerpt in the pdf file, instead of the image produced by that excerpt.
> 
> To do that, we may also need to refactor the current code a little bit. Currently the `pdf-file-name` is treated as something static and used as key in `imgToOcclusionArrHashMap`. We might want to change `imgToOcclusionArrHashMap` to something like a list of objects, where each object represents a set of occlusions, and has `image-path` as its property.
> 
> What do you think of this?

Sorry, it seems I messed up during the final touchups in that commit. I added a new commit with fixed for that. Can you take a look? Thanks!
