### ISSUE TITLE
Any options to run headless?

### ISSUE THREAD

**Issue by monk-blade** [debanjandhar12/logseq-anki-sync#2]

**Comment by debanjandhar12** [comment]
Can you please describe what you mean by headless?

Do you mean:
- Run outside logseq?
- Run inside logseq but without the icon toolbar? (for example from logseq's command palate?)

**Comment by monk-blade** [comment]
I want to sync it using VPS. I can run anki in the background. I will call anki sync api through command line. Command line app will be helpful.

**Comment by debanjandhar12** [comment]
Sorry at the moment there are no plans to support calling logseq anki sync through command line.
A lot of portions of the code calls the logseq api and replacing those would take a lot of time.
