### ISSUE TITLE
images don't show up properly (org mode)

### ISSUE THREAD

**Issue by junyounglees** [debanjandhar12/logseq-anki-sync#205]
After updating to v5.0.0. from v4.4.0 and syncing, image files in cards don't show up properly.

It seems that <img src> tag points to files in logseq assets folder like below. 
![CleanShot 2023-07-18 at 17 07 28@2x](https://github.com/debanjandhar12/logseq-anki-sync/assets/11092098/70f6d802-3510-440d-a2ec-725342143894)

In Config field, assets are missing.
![CleanShot 2023-07-18 at 17 18 05@2x](https://github.com/debanjandhar12/logseq-anki-sync/assets/11092098/3081202b-56c1-4ad7-bcb1-9dd69b96dba7)

In my logseq, I use org files.
<img width="767" alt="image" src="https://github.com/debanjandhar12/logseq-anki-sync/assets/11092098/3ec28377-4342-4649-b0c4-c405ae494ab6">

**Device Information (please complete the following information):**
 - OS with version: OSX
 - Logseq Anki Sync Plugin Version: 5.0.0.
 - Anki Version: 2.1.65 (aa9a734f)⁩

**Comment by debanjandhar12** [comment]
fixed in v5.0.1
