### ISSUE TITLE
字体问题

### ISSUE THREAD

**Issue by keen0309** [debanjandhar12/logseq-anki-sync#208]
在Logseq高亮红色和绿色，发送到anki不显示
![image](https://github.com/debanjandhar12/logseq-anki-sync/assets/103982843/42e6446c-1c0e-487d-954d-bd287bb45cfd)
插件用的是
![image](https://github.com/debanjandhar12/logseq-anki-sync/assets/103982843/dfa68100-a851-4521-8865-ef7fcec9d42f)

**Comment by debanjandhar12** [comment]
Duplicate of #216
