### ISSUE TITLE
Image Occlusion not working in ankiweb and anki mobile app

### ISSUE THREAD

**Issue by lukas-mertens** [debanjandhar12/logseq-anki-sync#209]
**Describe the bug**
For me, image occlusion cards sometimes don't work on mobile and on the ios app. I know that it worked in the past at one point, but I can't reproduce when it works and when it doesn't (yet). Maybe you can help me. This is the debugging I have done so far.

I added an image occlusion in logseq. After syncing to anki the card looks like this:
![image](https://github.com/debanjandhar12/logseq-anki-sync/assets/10901304/6549ad92-2ca6-4dd3-b7ae-09a6a48473d6)
This is correct and the expected behaviour. However, on ankiweb and mobile it looks like this:
![image](https://github.com/debanjandhar12/logseq-anki-sync/assets/10901304/d37967be-f281-48df-854c-8382ceb83696)

I did some digging and noticed that #main-content has visibility: hidden:
![CleanShot 2023-08-22 at 23 12 31](https://github.com/debanjandhar12/logseq-anki-sync/assets/10901304/9d56161b-23d1-415b-a430-20222d4c9a5a)

This seems to be from https://github.com/debanjandhar12/logseq-anki-sync/blob/0d06c0c25b03ca5a64ff20d4cc8e3c23884b13ad/src/templates/template.html#L8

When I disable it, I can at least see the cards content (revealed)
![CleanShot 2023-08-22 at 23 17 05](https://github.com/debanjandhar12/logseq-anki-sync/assets/10901304/08bfc7e7-aa50-483f-9fcc-56a53513529a)

Do you have any idea what is happening here?

**Device Information (please complete the following information):**
 - Logseq Anki Sync Plugin Version: [5.1.2]
 - Anki Version: [2.1.65]

**Comment by debanjandhar12** [comment]
Fixed with v5.2.0. This requires syncing again to take effect. Please re-open issue if that's not the case.
