### ISSUE TITLE
Suggestion for multiple decks in one page

### ISSUE THREAD

**Issue by chs33** [debanjandhar12/logseq-anki-sync#21]
right now on same page if you want to make some cards on one deck and some other cards on the other deck, looks to me you have to mark every card's deck in block property(can do one deck in batch by specifying deck in page property, but for the other deck you have to do it for every card).

Maybe have some feature like specifying deck in block property, and any card build under it (i.e. as a child block of this parent block) will share the same deck destination?

**Comment by debanjandhar12** [comment]
will be added in v2.5.0
