### ISSUE TITLE
Keyboard shortcut to sync

### ISSUE THREAD

**Issue by navakelvin** [debanjandhar12/logseq-anki-sync#210]
Hello.

What the title says. Can you add a customizable keyboard shorcut option to sync?

**Comment by junyounglees** [comment]
Temporary Solution:
1. Open logseq Command Pallete using Cmd+Shift+P  (or Ctrl+Shift+P in Windows)
2. Type 'Anki' and find 'Start Logseq to Anki Sync'
3. Press Enter

**Comment by debanjandhar12** [comment]
It is now possible to set keyboard shortcut:
![image](https://github.com/debanjandhar12/logseq-anki-sync/assets/49021233/b8aa9f76-688b-4eb8-b39f-e96b2e9b4af5)

**Comment by Bolb389** [comment]
It's awesome, thank you for this addition ! 🙏
