### ISSUE TITLE
Number list is not displaying

### ISSUE THREAD

**Issue by bolDeju** [debanjandhar12/logseq-anki-sync#220]
**Describe the bug**
When I try to sync logseq card with number list to anki, i don't get that numbered list of items. Just dots.
When I use logseq flashcards (inside app) number list is in place.

**Steps to Reproduce:**
1. create a card in logseq
2. do a normal card sync to anki
3. See error

**Expected behavior**
Anki card have a numbered list.

**Screenshots:**
![logseq_flashcard](https://github.com/debanjandhar12/logseq-anki-sync/assets/75179769/f9bf1407-aa29-4dd7-8b33-34444cdaed4a)
![anki_flashcard](https://github.com/debanjandhar12/logseq-anki-sync/assets/75179769/ee45d6be-14a7-40e4-8339-9b72ab88e5a2)
![image](https://github.com/debanjandhar12/logseq-anki-sync/assets/75179769/489724b5-a040-459b-98a6-405e3a51de98)

**Device Information (please complete the following information):**
 - OS with version: [EndeavourOS Linux x86_64]
 - Logseq Anki Sync Plugin Version: [5.3.0]
 - Anki Version: [2.1.66]
 - AnkiConnect Addon Version: [23.4.11.0]
 - Logseq Version: [0.9.19]

**Comment by debanjandhar12** [comment]
Support added in v6.1.0
