### ISSUE TITLE
Request support for Anki's {{furigana:Text}} annotation field

### ISSUE THREAD

**Issue by DreamAfar** [debanjandhar12/logseq-anki-sync#223]
**Describe the solution you'd like**
Anki supports displaying kana annotations in Japanese kanji. 

Simply add the tag {{furigana:Text}} to the template field to correctly display the complete kana in kanji, https://en.wikipedia.org/wiki/Furigana

The effect is similar to the `<ruby>`tag of html: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/ruby

However, every time the logseq update is synchronized to Anki, the {{furigana:Text}} template field will be reset to the default template by logseq-anki-sync.

![image](https://github.com/debanjandhar12/logseq-anki-sync/assets/69999980/9165b643-9f8b-4b7e-92c7-27c5bb1dc3c8)

![image](https://github.com/debanjandhar12/logseq-anki-sync/assets/69999980/8aa2c5a7-9866-4356-b414-c93516d87ea0)

In addition, I found that adding the {{furigana:Text}} field to Anki's template will cause the Image Occlusion cards of logseq-anki-sync to become invalid. I hope the conflict can be resolved.

**Describe how it will help your workflow**
It is hoped that logseq-anki-sync can provide a switch so that Anki's {{furigana:Text}} field can be retained in each update without having to manually edit the template every time.

**Describe alternatives you've considered**
If logseq-anki-sync adds Anki's {{furigana:Text}} field to the template and it is difficult to implement, can it be solved through the HTML `<ruby>` tag?

### logseq test text：
- Japanese Kanji Kana Tags 漢字[かんじ] #card
	- After adding the furigana field, the effect of kanji annotation 漢字[かんじ]

**Comment by debanjandhar12** [comment]
Will be released with next version.
