### ISSUE TITLE
Anki tags removed by logseq (each sync)

### ISSUE THREAD

**Issue by Nightwindx** [debanjandhar12/logseq-anki-sync#228]
**Describe the bug**
By default, the anki software tags the cards with "Leech" when you press "Again" a certain number of times on, 8 times by default. We lose this functionality since every time we sync from logseq to Anki the card gets updated by what is found in logseq, thus removing the "Leech" tag

**Expected behavior**
Any added tags (in Anki) to the cards' properties shall be preserved, if not by logseq, at least by Anki. "Leech" tag added manually in Anki to a card originally found in logseq shall always be present and not lost upon syncing from logseq to Anki

**Comment by debanjandhar12** [comment]
Weird. The plugin is not supposed to do that. Can you answer the question bellow:

- Is the tag in anki "Leech" or "leech"?
- Anki version?

**Comment by Nightwindx** [comment]
"Leech" with a capital L
Anki version: 23.10.1 Qt6

However, Anki is removing **all tags** added manually inside of Anki upon pressing the sync button in Logseq (I'm assuming the plugin has no pull requests to see what changes have been made to the card in Anki? I say this because editing a Logseq card **content** in Anki ends up getting deleted as well upon each sync from the plugin. 

In brief, any changes, to the best of my knowledge, made to a Logseq card inside of the Anki software, regardless of their nature, get deleted upon each sync.

**Comment by debanjandhar12** [comment]
Fixed in V6 (to be released tomorrow)
