### ISSUE TITLE
No Profile Determined

### ISSUE THREAD

**Issue by Nightwindx** [debanjandhar12/logseq-anki-sync#230]
**Describe the bug**
Not separating between profiles. Logseq syncs everything into one profile only with no possibility to determine the target profile

**Expected behavior**
If I have a deck X in profile X, I want the plugin to sync everything to deck X in that same profile X and not create a new deck Y in the current profile Y I am using. Logseq should know that it already has a deck X in profile X, and thus no need to create a new deck Y in Profile Y upon syncing. 

**How is this a problem?**
We create multiple profiles to separate between the type of activity we do. One profile could be used for language learning, while another could be used for studying university courses. Mixing the two activities creates a confusion in the "New" cards, the "Due", the "Reviews", the "Learn" and the "Total". It also creates a bias in the statistics of Anki in terms of "cards/minute" rate, "review intervals", "Future Due" and many others. 

**Device Information (please complete the following information):**
 - OS with version: [e.g. Windows 11 Home 22H2] 
 - Logseq Anki Sync Plugin Version: [5.5.0]
 - Anki Version: [23.10.1]
 - AnkiConnect Addon Version: [latest, I did not know where to see the version]
 - Logseq Version: [0.10.0]

**Comment by debanjandhar12** [comment]
Sorry, not a bug.

It was done intentionally to allow the user to sync cards from one graph to multiple anki profiles.
