### ISSUE TITLE
batch add 'tags' in a page (like setting deck::)

### ISSUE THREAD

**Issue by JaeyongMed** [debanjandhar12/logseq-anki-sync#232]
I want to add same tags for cards in a page
Exactly like this

deck::logseq
tag::headAndNeckAnatomy, Medicine

Quesiton1 #card
  Answer1(this card gets the tags above)

I want to manage cards by tag, not by deck.

**Comment by debanjandhar12** [comment]
you can use the following page properties (declare in first block in a page):
```
tags: tag1,tag2
```

**Comment by debanjandhar12** [comment]
Please re-open in case the above answer was not helpful.
