### ISSUE TITLE
Anki card contains "<b>:-></b>"

### ISSUE THREAD

**Issue by HeinzContiZacherl** [debanjandhar12/logseq-anki-sync#238]
**Describe the bug**
A clear and concise description of what the bug is: Anki card contains `<b>:-></b>` instead of `:->`

**Steps to Reproduce:**

1. On Logseq: create a card like this: <img width="314" alt="Test Card in Logseq" src="https://github.com/debanjandhar12/logseq-anki-sync/assets/33962661/f788c200-b8f7-4232-bcdc-124735607427">
2. Export card to Anki
3. See error: On Anki cards looks like this: <img width="933" alt="image" src="https://github.com/debanjandhar12/logseq-anki-sync/assets/33962661/c8d15e1c-63f9-4313-97cd-a411b9f30d5b">

**Expected behavior**
On Anki cards should look like this: <img width="933" alt="image" src="https://github.com/debanjandhar12/logseq-anki-sync/assets/33962661/5feebdf6-a180-458c-a8cf-196618e07a7c">

**Developer console screenshot:**
Please add a screenshot of the error in logseq's developer console if applicable. Logseq's developer console can be accessed by pressing `Ctrl + Shift + I`.

**Device Information (please complete the following information):**

-   OS with version: latest MacOS (18.12.23)
-   Logseq Anki Sync Plugin Version: (actual version on 18.12.23)
-   AnkiConnect Addon Version: (latest at 18.12.23)
-   Logseq Version: (latest at (18.12.23))

**Comment by HeinzContiZacherl** [comment]
Update: 19.12.23

The issue with "`<b>:-></b>`" appearing in Anki cards might stem from two factors. Firstly, in Logseq, "`:->`" is automatically converted to "`:→`", which could be happening before syncing with Anki, causing unexpected formatting. Secondly, there's an HTML code issue where HTML entities for bold tags are being rendered as actual tags. The problematic code is `<span>Systemmonitor anzeigen&lt;b&gt;:-&gt;&lt;/b&gt; {{c1::<code>top</code>.}}</span>`, which displays as "Systemmonitor anzeigen<b>:-></b> {{c1::top.}}". The solution is to remove the bold tag entities from the code, updating it to `<span>Systemmonitor anzeigen:-&gt; {{c1::<code>top</code>.}}</span>`, which should correctly display ":->" without bold formatting.

**Comment by HeinzContiZacherl** [comment]
Could it possibly be a solution to change add the following lines to your converter-code? 

`// Render the markdown
resultContent = Mldoc.export(
    "html",
    resultContent,
    JSON.stringify(mldocsOptions),
    JSON.stringify({}),
);

// Replace ":→" with ":->"
resultContent = resultContent.replace(/:→/g, ":->");`

**Comment by debanjandhar12** [comment]
Issue is occurring due to no space before ":->".

The bold tags are first being added here:
https://github.com/debanjandhar12/logseq-anki-sync/blob/2efe2f231b352c88572e563c91f73414ccb8eefe/src/notes/SwiftArrowNote.ts#L48

and then passed to:
https://github.com/debanjandhar12/logseq-anki-sync/blob/2efe2f231b352c88572e563c91f73414ccb8eefe/src/notes/SwiftArrowNote.ts#L59

The converter internally uses mldoc which require html code to be space separated. However, earlier, we didn't add space.

-------------------
Replacing the above line of SwiftArrowNote with below should fix it:
replacement += `${beforeArrowSpace}${beforeArrowSpace.endsWith(" ") ? "" : " "}<b>${g3}</b>${afterArrowSpace}`;

**Comment by HeinzContiZacherl** [comment]
Great! I just added a space before ":->" to my notes in Logseq and it worked. Now the Anki cards are correct. 

Do you think you could add this little change to future releases or mention the needed space on the documentation? I think that would improve your addon even further.

**Comment by debanjandhar12** [comment]
I'm glad the addon has been helpful for you. I have included the fix and will do a release with it included soon.
