### ISSUE TITLE
Add support for Note Type "Basic (type in the asnwer)"

### ISSUE THREAD

**Issue by aninternetuserx** [debanjandhar12/logseq-anki-sync#239]
Appologies if this was suggested before, but I searched and didn't find any issue
**Describe the solution you'd like**
Be able to make flashcards with the native Anki  "Basic (type in the answer)", maybe with some syntax similar to the one used with cloze cards. It could also be added as an option under "Select different field options to apply to Anki cards" since its a modification on the template

**Describe how it will help your workflow**
Most of my Anki cards are added throughout this great Logseq plugin, it'd be nice to be able to add this card type too since it would be be useful for learning coding: instead of just seeing the answer you could type it, very similar to a real case scenario and already developing the muscle memory. [This video explains how to use this card type for programming](https://youtu.be/lw5HsaFswEQ?si=56u2g5KMzo1xTtG6&t=438)  

**Describe alternatives you've considered**
Making "Basic" cards and just see the answer is working, but since I'm memorizing things I tend to type, it makes more sense to type it because it's closer to the realworld scenario I'm going to use
Thank you so much for making such an epic plugin :)

**Comment by debanjandhar12** [comment]
Type in answer support added in v6.2.0 (eta 2-3 days)
