### ISSUE TITLE
Using less then without space makes math invalid

### ISSUE THREAD

**Issue by Erroduct** [debanjandhar12/logseq-anki-sync#24]
**Describe the bug**
Whenever "<" is followed by another character without a space between them, the rest of the block's content is ignored. 
I have tried a few other operators, or moving the space and this issue seems to be limited to "<" without a space behind it.

**Example:**
![image](https://user-images.githubusercontent.com/39995623/150713472-48d215aa-3847-43cd-852d-031cee69b510.png)
![image](https://user-images.githubusercontent.com/39995623/150713485-ee385929-6d72-4d6f-9078-1e1f2201eb72.png)
![image](https://user-images.githubusercontent.com/39995623/150713506-466f68f1-282c-4114-8210-e17c85525722.png)

Rewriting the math part as `$x < a + y$` (with a space) will yield the correct result however.

**Device Information:**
 - OS with version: Linux (Ubuntu 20.04)
 - Logseq Anki Sync Plugin Version: v1.0.0
 - Anki Version: ⁨2.1.49
 - AnkiConnect Addon Version: Could not find a version number, update 2021-12-27T07:22
 - Logseq Version: 0.5.9

**Comment by debanjandhar12** [comment]
This has been fixed and will be included in v1.1.2 next week.
