### ISSUE TITLE
Cloze syntax rendered in parent blocks

### ISSUE THREAD

**Issue by Futur3r** [debanjandhar12/logseq-anki-sync#244]
**Describe the bug**
Anki render the syntax of clozes (i.e {{c2 word}}) of the parents of a block in flashcards.

**Steps to Reproduce:**
1. create a flashcard with clozes in logseq
2. create a flashcard with clozes as a child of the first one.
3. preview the second flashcard in anki.

**Expected behavior**
The blocks parent should not have any cloze syntax visible in anki.

**Device Information:**

- OS with version: Linux Mint 21
- Logseq Anki Sync Plugin Version: 6.0.0
- Anki Version: 2.1.54
- Logseq Version: 0.19.3

**Comment by CappieXL** [comment]
+1
