### ISSUE TITLE
Anki cards ignore styling and format for "input answer" resets with logseq sync

### ISSUE THREAD

**Issue by HeinzContiZacherl** [debanjandhar12/logseq-anki-sync#246]
**Describe the bug**
Styling added to anki cards doesn't affect the style of anki cards making it impossible to increase font size or other simple but useful styling. In addition to this the front and back templates get reseted to their default config every time one syncs anki from within logseq. One can not therefore in anki edit the templates to be able to write the answer for the cards questions like this "<span class="text"> {{cloze:Text}} </span>"

**Steps to Reproduce:**

LogSeq Plugin Sync resets anki template:
1. On Anki: Edit the front and back templates to enable "type in answer" with "<span class="text"> {{type:cloze:Text}} </span>"
2. On LogSeq sync notes with anki using the plugins default function.
3. On Anki: "<span class="text"> {{type:cloze:Text}} </span>" ist not anymore on the template. The template was reseted to its default.

Unable to modify styling on anki:
1. On LogSeq: Create Anki cards with the plugin.
2. In Anki: Try to modify the card styling. Like for example: Increasing the font size.
3. In Anki: Save your template changes.
4. In Anki: Nothing happens. Styling changes are ignored.

**Expected behavior**
Styling changes shouldn't be ignored and template changes shouldn't be reseted by new LoqSeg syncs.

**Developer console screenshot:**
Please add a screenshot of the error in logseq's developer console if applicable. Logseq's developer console can be accessed by pressing `Ctrl + Shift + I`.

**Device Information (please complete the following information):**

-   OS with version: latest MacOS (07.01.24)
-   Logseq Anki Sync Plugin Version: latest Plugin Version (07.01.24)
-   Anki Version: latest Anki Version (07.01.24)
-   AnkiConnect Addon Version: latest Addon Version (07.01.24)
-   Logseq Version: latest LogSeq Version (07.01.24)

**Comment by debanjandhar12** [comment]
Type in answer support added in v6.2.0 (eta 2-3 days)
