### ISSUE TITLE
Flashcards within blocks can't be synced into Anki properly

### ISSUE THREAD

**Issue by A-Z-X-R** [debanjandhar12/logseq-anki-sync#254]
**Describe the bug**

When you open a block, type some notes in, and put your flashcard inside the block (for organisation purposes), the plugin feeds the **entire** block, instead of just the plugin

**Expected behavior**
Just the flashcard should appear in Anki

**Developer console screenshot:**
Please add a screenshot of the error in logseq's developer console if applicable. Logseq's developer console can be accessed by pressing `Ctrl + Shift + I`.

There are no errors though...

**Device Information (please complete the following information):**

-   OS with version: Mac OS X 12.7.3 Monterey
-   Logseq Anki Sync Plugin Version: v6.1.0
-   Anki Version: 23.12.1
-   AnkiConnect Addon Version: I have no idea but it's the most recent one
-   Logseq Version: 0.10.7 (81)

**Comment by debanjandhar12** [comment]
You mean parent block content appears in anki cards? You can disable this behavior by toggling this plugin setting off:
![image](https://github.com/debanjandhar12/logseq-anki-sync/assets/49021233/e4bdb097-71f6-4ff5-a0a2-6f0b8e378799)

**Comment by A-Z-X-R** [comment]
> You mean parent block content appears in anki cards? You can disable this behavior by toggling this plugin setting off: ![image](https://private-user-images.githubusercontent.com/49021233/311443205-e4bdb097-71f6-4ff5-a0a2-6f0b8e378799.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAwNDA4NjcsIm5iZiI6MTcxMDA0MDU2NywicGF0aCI6Ii80OTAyMTIzMy8zMTE0NDMyMDUtZTRiZGIwOTctNzFmNi00ZmY1LWEwYTItNmYwYjhlMzc4Nzk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEwVDAzMTYwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAyMzM5YTMzNzNkNTUzMjM4YmY5MDdmZmE3NGUyMjlmNDE1ZGI1ZmNjNzFkMTllNTk5MzQyN2M5NTNmN2JlOWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.giweaBjM6-xVjrrwg1GA0AwHESMCxPl5hg9fQ7ImPBA)

Oh thank you, I never knew that! I've done it and it looks good for now. Closing!
