### ISSUE TITLE
Question: how to reproduce the hash of a note

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [debanjandhar12/logseq-anki-sync#262]
Hi,

[Omnivore](https://omnivore.app) is a FOSS app that allows to read articles and PDF and highlight them. They have a great addon to import the highlights automatically to anki.

I'm coding something to turn the article highlights straight to anki cards using my [LogseqMarkdownParser](https://github.com/thiswillbeyourgithub/LogseqMarkdownParser) to create cloze blocks that will be send by your addon straight to anki. (Btw if anyone is interested the WIP code is [here](https://github.com/thiswillbeyourgithub/LogseqMarkdownParser/blob/main/examples/omnivore_to_anki.py))

My issue is that I will inevitably change my code from time to time and this will modify the logseq page and blocks containing the flashcards. But given that the highlights themselves don't change I need to avoid at all cost having your addon think that the block was deleted as that would reset the anki reviews!

* My initial thinking was to set a `id:: ` property to the card block that would be a hash derived from the original article (so the hash should not vary when I modify the code) but I'm not sure it worked.
* I also tried looking at your code but am not sure I understand as hashing is used both to differentiate notes AND to see if the note needs reuploading (right?)

So my question is : **what do I need to keep constant in my cloze blocks to make sure your addon does not think the card was deleted?**

Thank you very much!

**Comment by thiswillbeyourgithub** [comment]
> So my question is : what do I need to keep constant in my cloze blocks to make sure your addon does not think the card was deleted?

Up :) if you find the time

**Comment by debanjandhar12** [comment]
- Logseq block id is one of the parts that is used for uniquely identifying a note. The other part is note type.  
In the plugin, this identifier is used for determining which notes need creation / deletion / **may need update**. Hence, for your case, as long as the id remains same, the corresponding note will not be deleted.
- The hash is only used for determining which notes **actually** need updating. The hash is simply a mathematical sum of block content in logseq.

**Comment by thiswillbeyourgithub** [comment]
Thank you very much. I think that's enough for me.
