### ISSUE TITLE
/ankitag popup to quickly add anki tags as block property

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [debanjandhar12/logseq-anki-sync#266]
**Describe the solution you'd like**
a "/ankitag" command that would popup a tag autocompleter and when selecting one add it as a property. Using [ankiconnect](https://foosoft.net/projects/anki-connect/) you can simply use the function `getTags` to get all the tags in the collection.

**Describe how it will help your workflow**
Currently I'm note even tagging my cards because they are too cumbersome to type. I have many cards and decks and my tags are nested.

**Describe alternatives you've considered**
I was expecting to find an addon that would enable pasting some frequent strings but couldn't find any. If you know of any please do tell me!

**Comment by debanjandhar12** [comment]
Something similar is in works and will arrive with next update approx.
