### ISSUE TITLE
Code blocks should escape all characters

### ISSUE THREAD

**Issue by Amparose** [debanjandhar12/logseq-anki-sync#269]
It seems that some special characters (`< > &`) that this plugin uses aren't being escaped when in a code fenced block.

Add a code fence block to Logseq with these commonly-used characters (ignore the backslashes to escape backticks):

```
\```js
< > &
\```
```

The resulting card in Anki ends up as:

```js
&lt; &gt; &amp;
```

When it should be:

```js
< > &
```

**Comment by Resia1** [comment]
I'm experiencing a similar issue. It seems to be a particular problem with HTML codeblocks. 😭

If I write the html code below in logseq and sync it to Anki, I get the following

```html
<!DOCTYPE html>
<title>Title</title>

<style>body {width: 500px;}</style>

<script type="application/javascript">
  function $init() {return true;}
</script>

<body>
  <p checked class="title" id='title'>Title</p>
  <!-- here goes the rest of the page -->
</body>
```

---

![image](https://github.com/debanjandhar12/logseq-anki-sync/assets/155310323/2e541243-5381-4950-bd0f-2d6afedecf47)
![image](https://github.com/debanjandhar12/logseq-anki-sync/assets/155310323/c4b136be-835e-4895-ba43-7b8ba3d3f986)


I think this is very much related to the issue you're describing.

**Comment by Resia1** [comment]
Hi, I've been studying SQL recently and found a similar error.

I am using version `v6.1.0.`

-
	- ### C
	  ```c
	  #include <stdio.h>
	  int main() { printf("%d\n", 5 < 10 && 10 > 5); return 0; }
	  ```
	- ### C++
	  ```cpp
	  #include <iostream>
	  int main() { std::cout << (5 < 10 && 10 > 5) << std::endl; return 0; }
	  ```
	- ### Java
	  ```java
	  public class Main {
	    public static void main(String[] args) { System.out.println(5 < 10 && 10 > 5); }
	  }
	  ```
	- ### Javascript
	  ```javascript
	  console.log(5 < 10 && 10 > 5);
	  ```
	  ```javascript
	  5 < 10
	  10 > 5
	  >
	  <
	  &
	  ```
	  ```js
	  < > &
	  ```
	  ```javascript
	  < > &
	  ```
	- ### Python
	  ```python
	  print(5 < 10 and 10 > 5)
	  ```
	- ### HTML
	  ```html
	  <!DOCTYPE html>
	  <html>
	  <body>
	  </body>
	  </html>
	  ```
	- ### SQL
	  ```sql
	  SELECT CASE WHEN 5 < 10 AND 10 > 5 THEN 'True' ELSE 'False' END AS result;
	  &
	  ```


![image](https://github.com/debanjandhar12/logseq-anki-sync/assets/155310323/d7fb75e4-2fb9-46e5-84f8-58e6c21a2608)


Other than SQL, <, >, & are properly represented in other languages.

I'm on 6.1.0, so javascript is also represented correctly.

javascript
![image](https://github.com/debanjandhar12/logseq-anki-sync/assets/155310323/e48086f1-0347-4ff3-8101-50b4f7e1d11e)

**Comment by debanjandhar12** [comment]
Fix will be released with next version.
ETA: next weekend.
