### ISSUE TITLE
[BUG] Children not included

### ISSUE THREAD

**Issue by monk-blade** [debanjandhar12/logseq-anki-sync#27]
**Describe the bug**
![image](https://user-images.githubusercontent.com/1335766/150960995-84bd3d36-da0e-4137-8b80-1f9f15931061.png)

**Steps to Reproduce:**
Generate cards.

**Expected behavior**
It must include all the children.

**Device Information (please complete the following information):**
 - OS with version: [e.g. Windows 11 Home 21H2] 
 - Logseq Anki Sync Plugin Version: [e.g.1.0.0]
 - Anki Version: [e.g. 2.1.49]
 - AnkiConnect Addon Version: [e.g. 2.1.0]
 - Logseq Version: [e.g. 0.5.9]

**Comment by debanjandhar12** [comment]
This is not a bug but is intended behavior. However, I recognize the need and am planning to let users overwrite this behavior. Please discuss over #28.
