### ISSUE TITLE
Logseq-Anki-sync does not work after Update

### ISSUE THREAD

**Issue by HerkulesX** [debanjandhar12/logseq-anki-sync#270]
**Describe the bug**
After updating Logseq an the plugin the syncronastion does not work anymore.
When I start the synchronizing, Logseq stops working and has to be closed by task manager. Restarting the PC doesn't help.
![image](https://github.com/debanjandhar12/logseq-anki-sync/assets/159530856/f94fa903-1d50-434b-bbd0-9d0e5d9cbb76)

**Steps to Reproduce:**

Start the Anki-Sync

**Expected behavior**
Usually it only should sync my flashcards towards Anki, but literally **nothing** happens

**Developer console screenshot:**
Does not open

**Device Information (please complete the following information):**

-   OS with version: Mac OS Sonoma 14.4.1
-   Logseq Anki Sync Plugin Version: v6.3.1
-   Anki Version: 23.12.1
-   AnkiConnect Addon Version: [e.g. 2.1.0]
-   Logseq Version: 0.10.9 (83)

**Comment by debanjandhar12** [comment]
Can you try syncing after toggling off this in settings:
![image](https://github.com/debanjandhar12/logseq-anki-sync/assets/49021233/566cb1cd-ffdc-4404-a27c-1b965efc57dd)

**Comment by HerkulesX** [comment]
Thank you! After toggling off an relinking the graph it's working again.

I only have one graph at this moment, so I can't tell, if it's limited to this graph or not.
