### ISSUE TITLE
Adding outline subcontents to Anki flashcards.

### ISSUE THREAD

**Issue by LoveOctocat** [debanjandhar12/logseq-anki-sync#28]
This is the Logseq page, which uses the `#card` tag.

![image](https://user-images.githubusercontent.com/19794638/151968905-c5d689ce-3cdd-4076-b68b-f796979a5f67.png)

This is a screenshot of Anki's Flashcard.

![image](https://user-images.githubusercontent.com/19794638/151968583-b28da4e2-aa6a-4b6d-97c3-6ca7df15a15f.png)

I would like to be able to include all subcontents under 11111 and 22222 in the anki flashcard. Do you have any plans to develop this feature?

---

I found this plugin of yours today. I'm back to using Logseq, thanks!

**Comment by debanjandhar12** [comment]
Thanks for the feature request. 
The current behavior is similar to Remnote and frankly I think it is better this way for srs (there was a research paper on it which I cant seem to find the link of anymore). However, I do recognize that in some use-cases showing sub-blocks can have advantages.

Here are my ideas for now:
- **Soln 1**: Use a depth property to indicate how many sub blocks to include.
   ```md
   depth:: 3
   ```
- **Soln 2**: Have some kind of tag? like #include-all?

What are your thoughts on these solutions? If you have some better solution or think that by default it would be better to include all sub-blocks, please mention.

**Comment by LoveOctocat** [comment]
I think the second method (`#include-all`) is simple and useful.

**Comment by WaytrueDeng** [comment]
I have the same problem in org mode, but I think may be set include all as the default is the better choice?

**Comment by debanjandhar12** [comment]
Feat added in v1.1.0. (https://github.com/debanjandhar12/logseq-anki-sync/releases/tag/v1.1.0)
