### ISSUE TITLE
Hide all parent blocks in the front. Only show the block of the card created.

### ISSUE THREAD

**Issue by LK0624** [debanjandhar12/logseq-anki-sync#288]
**Describe the solution you'd like**

right now there is a "#hide-when-card-parent" function.
but it only applys on one parent block.
I'd hope there to be something like 

e.g.
1) #card #hide-all-parent-front
2) #card #no-parent 
etc..

I.E only show the '#card' block or 'swift arrow block' on the front.

**Describe how it will help your workflow**

1)
in many cases, when creating atomic notes and atomic cards,
the parents include too much information and clues for the answers.

well, although it could be like created on a separate page link to exclude the parents,
but, this would be fine if not using anki pluggin for flashcard.
but when studying in anki, the page link would be quite tedious since you'd have to click to go to logseq and then click again on logseq to go to the page link.

but, I just hope that if this feature is included, 
then you could be much more flexible in making card structures
making the most of the outline feature of logseq with anki.

(there is similar function of this in Notion2Anki, adding some emojis for excluding parents)

2)
if I use the 
#hide-when-card-parent
then, it applys to all the nested blocks.
but what I'm requesting for is to add a tag to the block to hide parent for only that block.

ex.

if done like this.

0
      1 #hide-when-card-parent
            2-1 #card
            2-2 #card 

then the parent 1 is hided for both 2-1 and 2-2
but, if the requested feature I asked is applied.

0
      1
            2-1 #card
            2-2 #card #hide-all-parent-front

then the parent is hided only on 2-2.

**Describe alternatives you've considered**

creating a separate page link.

--------
sum up.
1. appear only the card made block on the front.
2. if parent depth could be set up as a card depth could be done like now, it would be more awesome.

**Comment by debanjandhar12** [comment]
Will be released in next version (eta: this weekend)

**Comment by LK0624** [comment]
Thank You for Implementing the Feature Request!


Thank you so much for considering and implementing the feature I requested.
I truly appreciate your responsiveness and willingness to improve the
plugin.

I hope this new feature will be beneficial not only for me but for other
users as well,

and I’m happy to have made a small contribution to the ongoing development
of the plugin.


I'm a user from Korea, and many members of our community (the Koreanki
community) are grateful for your efforts in making this open-source plugin.

It has been incredibly useful for us, and we appreciate your hard work and
dedication.


Thank you once again.

Best regards

2024년 10월 2일 (수) 오후 9:08, debanjandhar12 ***@***.***>님이 작성:
