### ISSUE TITLE
Advice on how to render a card within logseq

### ISSUE THREAD

**Issue by mochar** [debanjandhar12/logseq-anki-sync#291]
Hello and thanks for your wonderful plugin

For [my plugin](https://github.com/mochar/logseq-incremental-blocks) I would like the user to be able to review anki cards generated by your plugin from within logseq itself (using anki-connect).

I have attempted to render the html retrieved from anki in an iframe. Since it loads local js and css template files, I also had to retrieve the contents of these files and load them into the iframe. This kind of worked - however there was some utf-8 issues, and I also had to inject the images in manually which I didn't succeed in doing since some of your js code (reasonably) assumes it is stored locally. 

All in all I wasn't happy with the solution, as it felt kind of backwards to convert logseq content to html, [hack it together to display it nicely in anki](https://github.com/debanjandhar12/logseq-anki-sync/wiki/Structure-of-this-Plugin#rendering), and then reverse hack it to display it in logseq again, haha.

So I was wondering if you have any advice for me here. Perhaps there's a more elegant way to display the card's content in an iframe within logseq, but just by browsing your code I didn't have much luck in figuring this out myself.

Thanks!

**Comment by mochar** [comment]
@debanjandhar12 Thanks! No worries about late answers. -- Both approaches you suggested just render the markdown as is written down by the user, rather than what your library parses and shows in Anki, e.g. the clozes made with the `:->` syntax, and the image occlusions. Ultimately I am trying to render the cards as they are shown in anki, within logseq. Does it make sense?

**Comment by debanjandhar12** [comment]
@mochar 

Some pointers regarding working of this plugin that may be helpful if you insist on using the plugin's output:
- The plugin converts all swift cards (similarly for image occlusion, different cloze patterns, multilinecards) into anki cloze syntax. [https://github.com/debanjandhar12/logseq-anki-sync/tree/main/src/notes - getClozedContentHTML()]
- Anki needs cards to be in html format. The plugin converts markdown to html using  convertToHTMLFile of https://github.com/debanjandhar12/logseq-anki-sync/blob/main/src/logseq/LogseqToHtmlConverter.ts. It doesnt modify anki clozes {{c1:: content}} patterns so anki can handle clozes in it's own way.
- Rendering of clozes are mostly controlled by anki itself (i.e. {{c1::hello}} is shown as [...] in anki part is handler by anki itself). This needs to be re-implemented in ur side. 
- Using the styles and js from https://github.com/debanjandhar12/logseq-anki-sync/tree/main/src/templates and loading them in logseq  should do the trick of correct rendering of html generated by plugin correctly.

Ideally, it may be easier to go with my earlier recomended approach 2 as you will have more control and less dependency.

**Comment by mochar** [comment]
Thank you kindly for the pointers.

**Comment by mochar** [comment]
@debanjandhar12 I'm reading your html conversion code... you are a madman!
