### ISSUE TITLE
Plugin only renders one cloze per bullet point

### ISSUE THREAD

**Issue by busera** [debanjandhar12/logseq-anki-sync#3]
When a bullet point has multiple cloze, only one is rendered correctly:

Logseq:
Clustering is a [[unsupervised machine learning]] method where a {{cloze unlabeled}} dataset is grouped based on {{cloze similar patterns}} (or the lack of those), such as color, size, shape or behavior.

Anki:
Clustering is a [[unsupervised machine learning]] method where a {{c1::unlabeled}} dataset is grouped based on {{cloze similar patterns}} (or the lack of those), such as color, size, shape or behavior.

In Anki, the first cloze gets the **c1::**. The second cloze is not "transformed/rendered".
Normally, two options are possible for that case, either the second cloze also gets the **c1::** which means both cloze are hidden in the same card (review) or it gets the **c2::** which creates a second flashcard. I normally prefer the first approach.

Possible solution:
- as a new default: {{cloze a word}} and {{cloze another word}} --> uses **c::1** for both and creates one Anki flashcard
- {{cloze a word}}1 and {{cloze another word}}2 --> uses **c1::** and **c2::** and creates two Anki flashcards

**Comment by debanjandhar12** [comment]
This has been fixed and will be included in the next version. It was due to wrong regex for parsing cloze marco.

**Comment by busera** [comment]
Fantastic. Thx a lot.

**Comment by busera** [comment]
It works now, thanks. Each cloze is rendered as an extra flashcard.
