### ISSUE TITLE
is it possible to modify the font style of the card

### ISSUE THREAD

**Issue by chs33** [debanjandhar12/logseq-anki-sync#37]
try to modify the font style of the card via 

![image](https://user-images.githubusercontent.com/16418270/154505834-aebe80cf-0ceb-4e0d-b676-18a5ee22528a.png)

looks like only font-size property get recognized. the other property seems to be overwritten by the default setting. 

(right now the answer part in card are bold and blue, I am trying to make it not bold so that the actual bold part in answer can show up.)

**Comment by chs33** [comment]
follow up on this.
I managed solve this by modifying the setting in logseq_anki_sync.css which can be found under your Anki folder. for me it is ./Anki2/Username/collection.media/logseq_anki_sync.css

**Comment by debanjandhar12** [comment]
`./Anki2/Username/collection.media/logseq_anki_sync.css` will get overwritten everytime sync is done. This is not recomended to use.

Try using !important in the anki styling.

**Comment by chs33** [comment]
> `./Anki2/Username/collection.media/logseq_anki_sync.css` will get overwritten everytime sync is done. This is not recomended to use.
> 
> Try using [`!important`](https://www.w3schools.com/css/css_important.asp) in the anki styling.

doesn't work for me:
![image](https://user-images.githubusercontent.com/16418270/154528792-a6e53922-36c0-49d4-b19b-8d7a93a3cfe9.png)

**Comment by debanjandhar12** [comment]
> > `./Anki2/Username/collection.media/logseq_anki_sync.css` will get overwritten everytime sync is done. This is not recomended to use.
> > Try using [`!important`](https://www.w3schools.com/css/css_important.asp) in the anki styling.
> 
> doesn't work for me, still only the font size get picked up: ![image](https://user-images.githubusercontent.com/16418270/154528792-a6e53922-36c0-49d4-b19b-8d7a93a3cfe9.png)

add space before `!important`
