### ISSUE TITLE
Images are not included in Anki flashcards

### ISSUE THREAD

**Issue by busera** [debanjandhar12/logseq-anki-sync#4]
Hi, it seems that images are not transferred to Anki flashcards, yet.

Logseq:
- What is clustering (in machine learning)? #card #forward #machine_learning #data_mining
	- Clustering is a [[Unsupervised machine learning]] method where a **unlabeled** dataset is grouped based on **similar patterns** (or the lack of those), such as color, size, shape or behavior.
	- The clustering technique is commonly used for *statistical data analysis.*
	- `![_CJq-hx9heZVcwA85umP1f7Rslhmh1C83fcljitAVeyAHrLrY1tL0F70fsq_nvDFp9_oK8v2ryT0wSVpB4GASMpLhQhUiQKM7-ucgWBhHQso1ygO4uuf0LkJtT0uciod.png](../assets/_CJq-hx9heZVcwA85umP1f7Rslhmh1C83fcljitAVeyAHrLrY1tL0F70fsq_nvDFp9_oK8v2ryT0wSVpB4GASMpLhQhUiQKM7-ucgWBhHQso1ygO4uuf0LkJtT0uciod_1640042444230_0.png){:height 341, :width 500}`

Anki:
What is clustering (in machine learning)? #card #forward #machine_learning #data_mining

{{c1::
Clustering is a [[Unsupervised machine learning]] method where a unlabeled dataset is grouped based on similar patterns (or the lack of those), such as color, size, shape or behavior.

}}
{{c1::
The clustering technique is commonly used for statistical data analysis.

}}
{{c1::
_CJq-hx9heZVcwA85umP1f7Rslhmh1C83fcljitAVeyAHrLrY1tL0F70fsq_nvDFp9_oK8v2ryT0wSVpB4GASMpLhQhUiQKM7-ucgWBhHQso1ygO4uuf0LkJtT0uciod.png{:height 341, :width 500}

}}
<img width="712" alt="Screenshot 2021-12-21 104627" src="https://user-images.githubusercontent.com/20663020/146908905-57f76c2b-6940-479b-b651-774251996049.png">

**Comment by debanjandhar12** [comment]
Images are supposed to be transferred to Anki.
This seems like a edge case bug. Can you give me some more details? Specifically:
- OS with Version:
- Anki and AnkiConnect Version:
- Logseq Version:
- Logseq Anki Sync plugin Version:
- Screenshot of Logseq's Developer Console:

**Comment by busera** [comment]
Hi, thanks for the prompt response. 
Here are the details:


-     OS with Version: Windows 11 Home 21H2
-     Anki Version: 2.1.49 (dc80804a)⁩
-     AnkiConnect Version: **not sure where to find it**: I installed the add-on yesterday (2021-12-20; Add-on was updated 2021-07-14)
-     Logseq Version: 0.5.4
-     Logseq Anki Sync plugin Version: 0.2.2
-     Screenshot of Logseq's Developer Console: **not sure where to find the dev console**

**Comment by busera** [comment]
Hi, I think we can close the issue. I could solve the problem my replacing the png-file with a standard jpg file. I guess Anki does not support png with alpha channels.

Sorry for the troubles.
