### ISSUE TITLE
If use sub block as block add its upper blocl into breadcrumb

### ISSUE THREAD

**Issue by WaytrueDeng** [debanjandhar12/logseq-anki-sync#40]
**Describe the solution you'd like**
<img width="629" alt="image" src="https://user-images.githubusercontent.com/61548208/154826890-ff9b432f-3d33-42bc-be56-866dd25b9a34.png">
some thing like this  not just the page name , thanks a lot
**Describe how it will help your workflow**

**Describe alternatives you've considered**

**Comment by imxw** [comment]
I hope that the author will provide that feature, the reason why I use the flashcard feature of logseq, because it can provide more context

**Comment by debanjandhar12** [comment]
will look into this in next month.

**Comment by debanjandhar12** [comment]
![image](https://user-images.githubusercontent.com/49021233/163703667-d64ba138-4d0c-4d13-93d7-16c4705b638d.png)
This has been added in v2.3.0 (disabled by default, can be enabled from breadcrumb display settings of plugin settings page).
