### ISSUE TITLE
unknow html tag every where how can I fix it

### ISSUE THREAD

**Issue by WaytrueDeng** [debanjandhar12/logseq-anki-sync#46]
![image](https://user-images.githubusercontent.com/61548208/156362102-bdc07498-657e-42d6-b295-db226cf64ebd.png)

**Comment by debanjandhar12** [comment]
What are the contents of the logseq block which creates this card?
(Please copy paste the contents of the logseq block and not the screenshot)

**Comment by dfadsf32326** [comment]
I also have a similar problem,it is happen in v1.2.0
![image](https://user-images.githubusercontent.com/51404404/157187816-200fbe54-59a0-48af-bb73-e6a5c650d36c.png)
![image](https://user-images.githubusercontent.com/51404404/157187875-6d16fae0-24f5-43bf-9b92-2509893e0c4a.png)

{:block/uuid #uuid "61f53586-559e-4f30-917f-16875973ca26",
 :block/properties {:id "61f53586-559e-4f30-917f-16875973ca26"},
 :block/left {:db/id 8123},
 :block/refs [{:db/id 2}],
 :block/properties-order (:id),
 :block/children
 #{[:block/uuid #uuid "6224d89b-864f-4447-982a-75f40b9a6d85"]},
 :block/meta
 {:timestamps [], :properties [], :start-pos 28, :end-pos 128},
 :block/format :markdown,
 :block/content
 "我能做的任何我想要做到的事情 #card\nid:: 61f53586-559e-4f30-917f-16875973ca26",
 :db/id 8124,
 :block/path-refs [{:db/id 2} {:db/id 8119}],
 :block/parent {:db/id 8119},
 :block/unordered true, 
 :block/page {:db/id 8119}}

- 我能做的任何我想要做到的事情 #card
	- #人生

**Comment by debanjandhar12** [comment]
> I also have a similar problem,it is happen in v1.2.0 ![image](https://user-images.githubusercontent.com/51404404/157187816-200fbe54-59a0-48af-bb73-e6a5c650d36c.png) ![image](https://user-images.githubusercontent.com/51404404/157187875-6d16fae0-24f5-43bf-9b92-2509893e0c4a.png)
> 
>     * 我能做的任何我想要做到的事情 #card
>       
>       * #人生
> 
> 
> {:block/uuid #uuid "61f53586-559e-4f30-917f-16875973ca26", :block/properties {:id "61f53586-559e-4f30-917f-16875973ca26"}, :block/left {:db/id 8123}, :block/refs [{:db/id 2}], :block/properties-order (:id), :block/children #{[:block/uuid #uuid "6224d89b-864f-4447-982a-75f40b9a6d85"]}, :block/meta {:timestamps [], :properties [], :start-pos 28, :end-pos 128}, :block/format :markdown, :block/content "我能做的任何我想要做到的事情 #card\nid:: 61f53586-559e-4f30-917f-16875973ca26", :db/id 8124, :block/path-refs [{:db/id 2} {:db/id 8119}], :block/parent {:db/id 8119}, :block/unordered true, :block/page {:db/id 8119}}
> 
> {:block/uuid #uuid "6224d89b-864f-4447-982a-75f40b9a6d85", :block/left {:db/id 8124}, :block/refs [{:db/id 2072}], :block/children #{}, :block/meta {:timestamps [], :properties [], :start-pos 128, :end-pos 139}, :block/format :markdown, :block/level 2, :block/content "#人生", :db/id 8125, :block/path-refs [{:db/id 2072} {:db/id 3114} {:db/id 8119}], :block/parent {:db/id 8124}, :block/unordered true, :block/page {:db/id 8119}}
> 
> 问题不会发生在新创建的卡片中 The problem does not occur with newly created blocks

Thanks a lot. This seems to be due to a bug in [`mldocs`](https://github.com/logseq/mldoc/issues/120). I have created an issue there. If it doesn't work I will look into alternatives.

**Comment by debanjandhar12** [comment]
This has been fixed and will be included in V2.0.0 coming next week.
