### ISSUE TITLE
Image from PDF annotation

### ISSUE THREAD

**Issue by Tubo** [debanjandhar12/logseq-anki-sync#48]
**Describe the solution you'd like**
PDF area highlights gets synced as images to Anki. Currently highlighted images are displayed as [span].

**Describe how it will help your workflow**
Much more smooth process of card creation

**Describe alternatives you've considered**
No alternative at the moment.

**Comment by Tubo** [comment]
May I bump this feature request to a higher priority? This feature will allow people to make image-based cards on the fly. The only similar feature I've seen elsewhere is RemNote and Polar. 

This is the only feature that's needed for me to migrate my card creation workflow to Logseq. Thanks @debanjandhar12 for all the hardwork!

**Comment by debanjandhar12** [comment]
This is indeed high priority in my list as well. However, my schedule is kind of packed this month. I will take a look at this next month.
