### ISSUE TITLE
Extra:: below question / answer is not rendered in Anki

### ISSUE THREAD

**Issue by busera** [debanjandhar12/logseq-anki-sync#5]
<img width="609" alt="screen2" src="https://user-images.githubusercontent.com/20663020/146910051-142ccaf5-6873-4d5e-b703-09c8737fcc97.png">
<img width="498" alt="screen3" src="https://user-images.githubusercontent.com/20663020/146910053-b22d3eae-47c9-4ef4-b6ca-414a21620204.png">
Hi, I think the extra:: property is not recognized when putting it under the flash card question, below the answer. In Anki, the **Extra** field stays empty.

Loqseq:
- What is clustering (in machine learning)? #card #forward #machine_learning #data_mining
	- Clustering is a [[Unsupervised machine learning]] method where a **unlabeled** dataset is grouped based on **similar patterns** (or the lack of those), such as color, size, shape or behavior.
	- The clustering technique is commonly used for *statistical data analysis.*
	- extra:: Clustering is somewhere similar to the classification algorithm, but the difference is the type of dataset that we are using. In classification, we work with the labeled data set, whereas in clustering, we work with the unlabeled dataset.

Anki
What is clustering (in machine learning)? #card #forward #machine_learning #data_mining

{{c1::
Clustering is a [[Unsupervised machine learning]] method where a unlabeled dataset is grouped based on similar patterns (or the lack of those), such as color, size, shape or behavior.

}}
{{c1::
The clustering technique is commonly used for statistical data analysis.

}}
{{c1:: }}

**Comment by debanjandhar12** [comment]
This has been added in the latest release (v0.3.0).

**Comment by busera** [comment]
Hi, thanks a lot for the fast releases. How do I now integrate the extra information? I tested the two ways described in the how to page, however, the information is still not pushed in the "Extra" field of the Anki card.

**Comment by debanjandhar12** [comment]
> Hi, thanks a lot for the fast releases. How do I now integrate the extra information? I tested the two ways described in the how to page, however, the information is still not pushed in the "Extra" field of the Anki card.

It should work in preview and while reviewing cards. The extra property in Multiline cards doesn't use the extra field as each of Multiline card block's children can have an extra information and there is only one extra field.
Hence, it uses css to display extra property properly instead.

**Comment by busera** [comment]
Alright, thx. In this case it also works here as intended :-).
