### ISSUE TITLE
Get error: Unknown language "Plain text" when syncing

### ISSUE THREAD

**Issue by rumurphy** [debanjandhar12/logseq-anki-sync#53]
**Describe the bug**
When clicking the sync button in Logseq with Anki open I get pop-ups:
- Starting Logseq to Anki Sync for graph Logseq
- Error: Unknown language "Plain text" when syncing
- 
**Steps to Reproduce:**
1. Click Anki sync button in Logseq with Anki open
2. See error pop-up - Error: Unknown language "Plain text" when syncing
3. New cards do not show up in Anki

**Expected behavior**
Expecting a successful sync without error

**Device Information (please complete the following information):**
 - Windows 11
 - Logseq Anki Sync Plugin Version: 1.2.2
 - Anki Version: 2.1.49
 - AnkiConnect Addon Version: newest as of 3/11/22
 - Logseq Version: 0.6.2

**Comment by debanjandhar12** [comment]
Can you give me a screenshot of your developer console?

Steps to take ss:
1) Open logseq and press `Ctrl + Shift + I`
2) Open anki and click sync.
3) Take screenshot of output in the developer console.
