### ISSUE TITLE
won't render hiccup in anki card

### ISSUE THREAD

**Issue by wenjing100** [debanjandhar12/logseq-anki-sync#56]
The plugin is super good and I like it soooo much !

I dont know if it is a bug lol...
**my log in logseq**
![image](https://user-images.githubusercontent.com/55542032/158947810-84489925-c835-4eeb-9f7d-38f87d187cd9.png)
**render in logseq**
![image](https://user-images.githubusercontent.com/55542032/158947835-a1c86e6c-8518-4c7c-8c0b-ee9e4e18e7f5.png)

**what I got in anki**
![image](https://user-images.githubusercontent.com/55542032/158947878-382f81be-0cd3-47e7-82cc-92e84d87b2d8.png)

**Device Information (please complete the following information):**
 - OS with version: [e.g. Windows 11 Home 21H2] 
 - Logseq Anki Sync Plugin Version: [e.g. 0.3.3]
 - Anki Version: [e.g. 2.1.49]
 - AnkiConnect Addon Version: [e.g. 2.1.0]
 - Logseq Version: [e.g. 0.5.9]

**Comment by debanjandhar12** [comment]
added in v3.2.0
