### ISSUE TITLE
Text color is black in the dark theme

### ISSUE THREAD

**Issue by jakeoung** [debanjandhar12/logseq-anki-sync#6]
Thanks for this useful plugin. I usually use the dark theme, but I couldn't read the text since its color is on black. This issue appears also in the Obsidian.

**Comment by YuhomC** [comment]
Hi, 
add the line below to your anki card style will solve this issue.
`.nightMode .text {
    color: white !important;
}
`

**Comment by jakeoung** [comment]
Wow, thanks a lot!

**Comment by debanjandhar12** [comment]
> ```
> .nightMode .text {
>     color: white !important;
> }
> ```

Thanks, I will include the line the plugin itself and this should be available once mldocs-rendering is merged.
