### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading )

### ISSUE THREAD

**Issue by AngryAccelerated** [debanjandhar12/logseq-anki-sync#60]
![bug](https://user-images.githubusercontent.com/13927622/162562348-637a7c21-1582-439d-951b-7976d2dfe536.gif)

 - OS with version: [e.g. Windows 11] 
 - Logseq Anki Sync Plugin Version: [e.g. 0.3.3]
 - Anki Version: [e.g. 2.1.50]
 - AnkiConnect Addon Version: [e.g. 2.1.0]
 - Logseq Version: [e.g. 0.5.9]

**Comment by debanjandhar12** [comment]
Can you give me a screenshot of your developer console?

Steps to take ss:
1) Open logseq and press `Ctrl + Shift + I`
2) Open anki and click sync.
3) Take screenshot of output in the developer console. 

Also, which logseq version and what OS are you using?

**Comment by AngryAccelerated** [comment]
> 

Anki: 2.1.50[Qt 6]
Logseq: 0.6.5
OS: Windows 11

![123](https://user-images.githubusercontent.com/13927622/162563969-f15ff355-acf8-4b02-afc8-6ac03aec9e4a.png)

**Comment by debanjandhar12** [comment]
> > 
> 
> Anki: 2.1.50[Qt 6] Logseq: 0.6.5 OS: Windows 11
> 
> ![123](https://user-images.githubusercontent.com/13927622/162563969-f15ff355-acf8-4b02-afc8-6ac03aec9e4a.png)

Please revert back to 2.1.49 or wait for 2.1.51. There is a bug in anki which causes ankiconnect plugin to malfunction.
