### ISSUE TITLE
Error: Unknown language: "elixir"

### ISSUE THREAD

**Issue by zvmaz** [debanjandhar12/logseq-anki-sync#63]
**Describe the bug**
Cannot export cards to Anki, shows **Error: Unknown language: "elixir"** in popup. 

**Steps to Reproduce:**
Just clicking on the Anki-Sync button. 

**Developer console screenshot:**
Please add a screenshot of the error in logseq's developer console if applicable. Logseq's developer console can be accessed by pressing `Ctrl + Shift + I`.

**Device Information (please complete the following information):**
 - OS with version: [Fedora 36] 
 - Logseq Anki Sync Plugin Version: [2.3.0]
 - Anki Version: [2.1.5]
 - AnkiConnect Addon Version: [2.1.0]
 - Logseq Version: [0.6.6]
![Screenshot from 2022-04-19 17-01-40](https://user-images.githubusercontent.com/50499302/164046534-2cc0859e-9d02-41bd-bbc8-837fa85ac206.png)

**Comment by zvmaz** [comment]
As far as I know, Elixir is not supported yet in Logseq, but I nonetheless add Elixir code blocks in anticipation.

**Comment by debanjandhar12** [comment]
> As far as I know, Elixir is not supported yet in Logseq, but I nonetheless add Elixir code blocks in anticipation.

Can you show me an example of how an Elixir code block looks like? It would also be great if you can sent the content of logseq block which seems to be causing the problem.

**Comment by zvmaz** [comment]
I just create an empty new graph, with a new page, and two cards. It exports fine. 

![image](https://user-images.githubusercontent.com/50499302/164054531-84d81d5c-cef3-46f7-b937-385a17da278d.png)

The problem was with the page I was working on: a blank space right after "```elixir " part of the code block syntax. I removed them in my page, and now it exports fine.

It was not obvious because even though there was a blank space, the code block renders fine (without highlighting since it's not supported yet). 

Thank you for you help!
