### ISSUE TITLE
Selective sync!

### ISSUE THREAD

**Issue by pinarhorum** [debanjandhar12/logseq-anki-sync#64]
This amazing plugin transforms ALL of the cards on logseq which are tagged with #card to anki if you press the logseq-anki-sync-icon.
 
However, I would find it really usefull if you could have cards on logseq which wouldnt be transformed to anki. Maybe you could achieve this with having the #anki tag. All the blocks which have this tag would be transformed to anki while the #card tagged cards would remain on logseq. 

![image](https://user-images.githubusercontent.com/103883430/164785330-bfb36bd9-94b5-484a-af66-c8252b50577e.png)

**Comment by debanjandhar12** [comment]
Cards can now be prevented from syncing by using the `#no-anki-sync` tag from v5.3.0 onwards.
