### ISSUE TITLE
Exclude template from synced cards

### ISSUE THREAD

**Issue by szaffarano** [debanjandhar12/logseq-anki-sync#65]
**Describe the solution you'd like**
To create new flashcards, I use a Logseq template, and I'd like to exclude it from the cards to be synced with Anki since it's just a template, not a "real" flashcard.

**Describe how it will help your workflow**
My Anky decks won't be polluted with a spurious card.

**Describe alternatives you've considered**
1. Not include the `#card` tag in my template
2. Just ignore the synced template card in Anki

**Comment by debanjandhar12** [comment]
will be added in next version

**Comment by szaffarano** [comment]
Thanks @debanjandhar12 !!

**Comment by onehr** [comment]
> will be added in next version

Hi, first of all, thanks for the effort.

I'm currently using v4.0.4, was it already implemented? If so, how can I enable it to exclude template card?
