### ISSUE TITLE
Image are not displayed when using org mode format.

### ISSUE THREAD

**Issue by thales51064** [debanjandhar12/logseq-anki-sync#67]
**Describe the bug**
The images when making a flashcard with org mode format in logseq are not transfered to anki.

**Steps to Reproduce:**

- Using org mode format in logseq setting.

- Making a card with an image and sync with the addons will convert `[[../assets/image.jpg]]` to a broken link in anki like the following `<a href="logseq://graph/logseq?page=..%2Fassets%2Fimage.jpg" class="page-reference">../assets/Logseq_image.jpg</a></p>`. To note: the file also doesn't exist in anki assets folder.

**Expected behavior**

- Proper image file transfer and correct anki render: `[[../assets/image.jpg]]`to `<img src="..%252Fassets%252Fimage.jpg" title="image.png">`

**Device Information (please complete the following information):**
 - OS with version: [e.g. Windows 10] 
 - Logseq Anki Sync Plugin Version: [v2.6.3]
 - Anki Version: [2.1.49]
 - AnkiConnect Addon Version: []
 - Logseq Version: [0.6.4]

**Comment by debanjandhar12** [comment]
Will be available in next version.
