### ISSUE TITLE
Add a backlink to edit the Anki card in Logseq

### ISSUE THREAD

**Issue by pat-richter** [debanjandhar12/logseq-anki-sync#69]
**Describe the solution you'd like**
The sync plugin should add an option, which adds a link to the "orignal" Logseq block to each Anki card.

**Describe how it will help your workflow**
I've just starting with PKM software. First stop was Notion. Someone created 2anki.net (thanks!) and there is a smart option: You can have a backlink in your Anki card, so if you find an issue while studying, you can click the link, Notion will open, you change the mistake THERE and can sync it next time.

So you still have one source of truth, but you can easily edit cards on the go.

**Describe alternatives you've considered**
There is an issue which asks for 2-way-sync, but this will add problems and therefore seems not to become implemented: https://github.com/debanjandhar12/logseq-anki-sync/issues/34

The backlink solution seems like a good workaround with minimal afford.

**Comment by thiswillbeyourgithub** [comment]
(Just chiming in to say that the other way around can be done : a link from logseq to anki using [guiBrowse](https://github.com/FooSoft/anki-connect) to open directly the right card. I don't know if this is already implemented in logseq-anki-sync though)

**Comment by debanjandhar12** [comment]
> The backlink solution seems like a good workaround with minimal afford.

I agree. Will add it in v2.7.0.


> (Just chiming in to say that the other way around can be done : a link from logseq to anki using [guiBrowse](https://github.com/FooSoft/anki-connect) to open directly the right card. I don't know if this is already implemented in logseq-anki-sync though)

It is already implemented. It is named "Preview note in anki" and needs to be enabled from settings (disabled by default).

**Comment by thiswillbeyourgithub** [comment]
Will it be possible to make those backlinks work on android using ankidroid?

**Comment by debanjandhar12** [comment]
> Will it be possible to make those backlinks work on mobile too? I think they will be tremendously useful as finding stuff is always faster on the computer.

They currently don't work as logseq doesn't support logseq uri in android yet (its in works).

**Comment by debanjandhar12** [comment]
Will be included in next version.

**Comment by thiswillbeyourgithub** [comment]
Thanks a lot for all the hard work! I'm extremely appreciative.
