### ISSUE TITLE
URL Schemes in Logseq block content were broken in Anki cards 

### ISSUE THREAD

**Issue by why8023** [debanjandhar12/logseq-anki-sync#74]
**Describe the bug**
The MarginNote3 URL Schemes were broken after converting to Anki.
Specifically, see the below pictures:
This is original content in Logseq:
![image](https://user-images.githubusercontent.com/22267652/172521856-6ceb2ab2-f2b6-4d1f-896c-c5830a0518e9.png)
This is Anki card content, and  I have labeled  the broken  URL Scheme with arrows 
![image](https://user-images.githubusercontent.com/22267652/172522537-1fa71a76-f5af-4b91-91cc-c9b84b5a7a08.png)

**Device Information (please complete the following information):**
 - OS with version: macos 12.2.1
 - Logseq Anki Sync Plugin Version: 2.72
 - Anki Version: 2.4.19
 - AnkiConnect Addon Version: Latest
 - Logseq Version:0.7.2

**Comment by debanjandhar12** [comment]
Related to https://github.com/logseq/mldoc/issues/123

**Comment by cnrpman** [comment]
> Issue can be closed: Logseq 0.9.1 and Mldoc 1.5.3 parses url correctly:

https://github.com/logseq/mldoc/issues/123#issuecomment-1504739916

**Comment by keen0309** [comment]
Hello, when will there be an update? I see the URL issue has been fixed. When will the update be released?https://github.com/debanjandhar12/logseq-anki-sync/issues/74

**Comment by debanjandhar12** [comment]
> Hello, when will there be an update? I see the URL issue has been fixed. When will the update be released?#74

Tomorrow if there are no bugs, otherwise after 3 - 4 days
