### ISSUE TITLE
Can not open logseq by clicking "open block in logseq"button ➡️

### ISSUE THREAD

**Issue by Pikakakaka** [debanjandhar12/logseq-anki-sync#76]
**Describe the bug**
Can not open logseq by clicking "open block in logseq"button(➡️)

I guess it is caused by `window.open()` in _logseq_anki_sync.js

> `window.open()` does not work in a card template on Anki 2.1

I chaneged `window.open()` into
```javascript
const block_link = document.createElement("a");
block_link.href = `${link.href.match(/logseq:\/\/graph\/.*\?/)}block-id=${uuid}`
block_link.click()
```
it worked.

**Steps to Reproduce:**
 In anki, nothing happened after clicking "open block in logseq"button(➡️)

**Expected behavior**
open logseq and locate the block

**Developer console screenshot:**

**Device Information (please complete the following information):**
 - OS with version: Windows 10 Home 21H2
 - Logseq Anki Sync Plugin Version: 2.8.3
 - Anki Version: 2.1.49
 - AnkiConnect Addon Version: 2.1.0
 - Logseq Version: 0.7.3

**Comment by debanjandhar12** [comment]
Sorry for the delay (I had exams). I have included it and will release next version soon.
