### ISSUE TITLE
"model was not found" message

### ISSUE THREAD

**Issue by fmreda23** [debanjandhar12/logseq-anki-sync#8]
A window displays: "model was not found" while the note type exists on Anki

**Comment by debanjandhar12** [comment]
Can you give me some more details? Specifically:
- OS with Version:
- Anki and AnkiConnect Version:
- Logseq Version:
- Logseq Anki Sync plugin Version:
- Graph Name and Note type name:
- A screenshot of the error:
- Screenshot of Logseq's Developer Console:
