### ISSUE TITLE
Is it possible to make use of tags?

### ISSUE THREAD

**Issue by Vitorvlv** [debanjandhar12/logseq-anki-sync#87]
I heavily use tags on my anki setup, so I'm wondering if there's a way to set the tags for my cards on logseq, and when I sync them to Anki they are already correctly tagged.

**Comment by debanjandhar12** [comment]
At the moment, it is only possible via tags property in logseq:
```
tags:: geography, gk 
{{c1 Tokyo::what city?}} is the capital of Japan.
```
![image](https://user-images.githubusercontent.com/49021233/182579194-feabb21a-a69a-41e6-b809-83e636fb2279.png)
