### ISSUE TITLE
Always generating an extra card ending with blank knockout content

### ISSUE THREAD

**Issue by fengqiii** [debanjandhar12/logseq-anki-sync#93]
**Describe the bug**
Using this plugin will always generate an extra card. This is true for each **cloze** card, ending with `{{c1::}}`. This should not be a feature but a bug, right? How to solve it?

**Steps to Reproduce:**
just use the plugin as usual🥲
this is the card I excepted

<img width="539" alt="截屏2022-08-05 00 32 25" src="https://user-images.githubusercontent.com/75001434/182904448-875933bf-6818-4063-8cfa-8a7000fb0c33.png">

this is the card I hadn't excepted

<img width="546" alt="截屏2022-08-05 00 32 34" src="https://user-images.githubusercontent.com/75001434/182904689-92e05ebf-6df8-4f02-9751-1ec8ba9e8470.png">

**Developer console screenshot:**
<img width="1352" alt="截屏2022-08-05 00 44 00" src="https://user-images.githubusercontent.com/75001434/182905484-d25d31f8-68d5-49d9-8c90-eb72271f46e0.png">

**Device Information (please complete the following information):**
 - OS with version: macOS 13.0 Beta
 - Logseq Anki Sync Plugin Version: 3.2.0
 - Anki Version: 2.1.54
 - AnkiConnect Addon Version: [e.g. 2.1.0]
 - Logseq Version: 0.7.9

**Comment by debanjandhar12** [comment]
Can you provide the block content so that I can reproduce the issue?

**Comment by debanjandhar12** [comment]
fixed. Those additional card(s) will be deleted on next sync after v3.2.2 is out.
