### ISSUE TITLE
additional card for cloze 

### ISSUE THREAD

**Issue by chs33** [debanjandhar12/logseq-anki-sync#95]
**Describe the bug**
The current release (v3.2.0) nicely solves my previous request: https://github.com/debanjandhar12/logseq-anki-sync/issues/16#issue-1102598977,
but looks like it gives rise to problem of failure of properly handling genuine cloze card:

For a regular cloze card it will generate two cards, one of them is not wanted. 

**Steps to Reproduce:**
in logseq 
![image](https://user-images.githubusercontent.com/16418270/183308740-8cd9fdce-4cad-4147-a675-412a32504da0.png)

in anki it will produce two cards:
this card is wanted
![image](https://user-images.githubusercontent.com/16418270/183308770-2304658a-f0cb-40ff-ad3d-75e57e474b0a.png)

this card is not:
![image](https://user-images.githubusercontent.com/16418270/183308824-dc34daa4-e64f-40c6-8cb9-7648b2a95ad9.png)

**Comment by debanjandhar12** [comment]
fixed. Those additional card(s) will be deleted on next sync after 3.2.2 is out.
